### PR TITLE
added intl install for php-worker

### PR DESCRIPTION
**Pull request by Silassiai**
## Description
This PR allows to install intl in php-worker.

## Motivation and Context
(https://github.com/egulias/EmailValidator) requires PHP Intl

## Types of Changes
- [] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Definition of Done Checklist:

- [x] I've read the [Contribution Guide](http://laradock.io/contributing).
- [] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by Silassiai** [comment]
@bestlong do you know why the failures fail on INSTALL_LARAVEL_ENVOY ?

**Comment by parallels999** [comment]
@bestlong is #3333 fixing INSTALL_LARAVEL_ENVOY??

**Comment by erikn69** [comment]
https://github.com/php-zookeeper/php-zookeeper/pull/55

@Silassiai ZOOKEEPER is not compatible with php 8.2 yet

**Comment by Silassiai** [comment]
@bestlong ahh ok... thank you for merging this PR! :-D

**Comment by bestlong** [comment]
> @bestlong is #3333 fixing INSTALL_LARAVEL_ENVOY??

yes

**Pull request merged**
