### PR TITLE
improved readme commands

### PR DESCRIPTION
**Pull request by AminMkh**
would be easier to actually ssh into containers using docker-compose. using
```
docker-compose exec nginx bash
```
for instance.

### CODE REVIEW

**Comment by Mahmoudz** [comment]
@AminMkh still haven't merged this because it didn't worked on my computer, I though you probably had an updated version of docker compose. I was waiting to update mine, test it, confirm it's working and merge. Sorry for taking too long since I'm very busy these days working on some projects.. Thanks for your contributions :)

**Comment by AminMkh** [comment]
all good, it is a new feature, and even the docker website's documentation isn't updated yet.

I can only see it [here](https://docs.docker.com/compose/reference/exec/) 
but not [here](https://docs.docker.com/compose/reference/overview/) nor [here](https://docs.docker.com/compose/reference/)

```
docker-compose -v
docker-compose version 1.7.1, build 0a9ab35
```
```
docker-compose
Commands:
  build              Build or rebuild services
  config             Validate and view the compose file
  create             Create services
  down               Stop and remove containers, networks, images, and volumes
  events             Receive real time events from containers
  exec               Execute a command in a running container
  help               Get help on a command
  kill               Kill containers
  logs               View output from containers
  pause              Pause services
  port               Print the public port for a port binding
  ps                 List containers
  pull               Pulls service images
  restart            Restart services
  rm                 Remove stopped containers
  run                Run a one-off command
  scale              Set number of containers for a service
  start              Start services
  stop               Stop services
  unpause            Unpause services
  up                 Create and start containers
  version            Show the Docker-Compose version information
```

**Comment by Mahmoudz** [comment]
Hi @AminMkh, I will close this PR in favor of #115 as it worked just fine!

**Comment by Mahmoudz** [comment]
These changes are now implemented in LaraDock 4.
Many thanks.

**Pull request closed without merging**
