### PR TITLE
correct xdebug sed in workspace

### PR DESCRIPTION
**Pull request by ciliehub**
wasn't able to (x)debug in workspace, because xdebug did not get enabled. Corrected the sed command...

### CODE REVIEW

**Comment by mikeerickson** [comment]
We should test this from a scratch install to make sure the entire process is working.  I know there has been a lot of work lately around this functionality, need to make sure the documentation is up-to-date to date as well.

@winfried-van-loon @Mahmoudz Do you know if the documentation of using xDebug is current?

**Comment by mikeerickson** [comment]
@ciliehub We appreciate the PR.  If you have performed the installation from scratch and are able to successfully debug, would like to know precise steps (we have had a large number of users who cant make it work)

**Comment by ciliehub** [comment]
@mikeerickson 
> and are able to successfully debug
I made this work especially for (php)unittesting
> would like to know precise steps
I'll try to find some time to sum this up in the next few days (although the documentation was very close already)

some patience please

**Comment by Mahmoudz** [comment]
@ciliehub @mikeerickson I believe the xDebug documentation need some serious update. Everyone will appreciate a better documentation for this tool. I'll merge this now since it's unrelated, and I hope someone is currently using it can update the docs. Thanks

**Pull request merged**
