### PR TITLE
Fixed Change wrong project name.

### PR DESCRIPTION
**Pull request by appleboy**

### CODE REVIEW

**Comment by Mahmoudz** [comment]
@appleboy thank you for your contributions.

Can you please pull the latest master branch (v2.4.3) and confirm your last 2 PR are working correctly. Since I had to fix the conflict manually..
Try rebuilding your workspace container (with --no-cache) to see if you get no errors playing with xdebug and nvm..

Thanks

**Comment by appleboy** [comment]
@Mahmoudz OK. I will check again.

**Comment by appleboy** [comment]
It is working on `v2.4.3` tag branch.

screen shot 2016-06-23 at 11 01 12 am

**Comment by Mahmoudz** [comment]
@appleboy Thank you man, you are awesome.

**Pull request merged**
