### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by innerspirit**
The link did not work due to a bad url

### CODE REVIEW

**Comment by Mahmoudz** [comment]
@innerspirit can you please do another one and change the phrase to this:

Use the [LaraDock-ToolBox](https://github.com/laradock/laradock/tree/LaraDock-ToolBox) branch. _(outdated)_

**Comment by innerspirit** [comment]
Alright. BTW the "Upgrading Laradock" link doesn't work. What is it supposed to point to?

**Comment by wallcrosstype** [comment]
I'm trying to report link typo but found this first so maybe here is appropriate ?

> Visit the *Laradock-ToolBox* branch. (outdated)

at http://laradock.io/getting-started/#usage still point to small "d" url
`https://github.com/laradock/laradock/tree/Laradock-ToolBox`

**Comment by Mahmoudz** [comment]
do you mean this one http://laradock.io/documentation/#upgrading-laradock ? this one is working for me!

**Comment by wallcrosstype** [comment]
nope I really means http://laradock.io/getting-started/#usage
the anchor link in line  "Use Laradock v3.*. Visit the `Laradock-ToolBox` branch. (outdated)"
point to `https://github.com/laradock/laradock/tree/Laradock-ToolBox` (incorrect)
instead of `https://github.com/laradock/laradock/tree/LaraDock-ToolBox`

while this pull suppose to already fix this, somehow in live document and branch master still incorrect

**Comment by Mahmoudz** [comment]
lol that's wired

**Comment by wallcrosstype** [comment]
I think I know, please check commit fef6ec86b361b5d039da21b9d1b60c6deff80d25

**Pull request merged**
