### PR TITLE
(Workspace) Update NPM to v3 after install

### PR DESCRIPTION
**Pull request by Kauhat**
The version of NPM installed by the system package manager (~1.3.10) is quite old now, and is not supported by some recent tools. This patch updates it to the most recent version before installing Gulp and Bower.

I've also moved the symlink up higher as NPM encounters issues after the upgrade without this.

Thanks!

### CODE REVIEW

**Comment by Mahmoudz** [comment]
@Kauhat thanks for your contribution.
I won't be able to test this on my own machine at the time and I don't want to delay anyone from having this change. Can you confirm this is working flawlessly on your own computer?! In order to merge it blindly!

**Comment by appleboy** [comment]
@Mahmoudz @Kauhat 

I would like to create new PR about support `nvm` tool which provide stable node version and npm@3 version and remove install node from `apt` command.

Any thoughts?

**Comment by Mahmoudz** [comment]
@appleboy let's see what is @Kauhat opinion.

**Comment by Kauhat** [comment]
@appleboy That's probably a good idea - it would be handy to have `nvm` already installed.

@Mahmoudz I've rebuilt my dev environment and things have gone smoothly on my end. If it's alright with you folks I'll double check the patch at home later on and let you know how things go.

**Comment by appleboy** [comment]
@Kauhat If you agree my approach, I think you can close this issue. I will implement the nvm tool on Docker right now and send the new pull request to support npm@3 version.

**Comment by Kauhat** [comment]
@appleboy Okay then, let me know if I can help you test your request once you're ready.

**Comment by appleboy** [comment]
@Kauhat Thanks.

**Pull request closed without merging**
