### PR TITLE
fixes #1847 404 on worksapce xdebug installation

### LINKED ISSUE #1847: Php 7.2 XDebug install error
### Info:
- Docker version: 
Docker version 17.12.1-ce, build 7390fc6
- Laradock commit: 
9cfe5c61565a77b4da40817f3e1d45e18ef5920d
- System info (Mac, PC, Linux): 
Ubuntu 18.04
- System info disto/version: 

### Issue:
I can't install Xdebug when I'm using php 7.2
_____

### Expected behavior:
Successful build
_____

### Reproduce:
PHP_VERSION=7.2
WORKSPACE_INSTALL_XDEBUG=true
_____

### Relevant Code:

```
Step 60/179 : ARG INSTALL_XDEBUG=false
 ---> Using cache
 ---> f1c0af719c3b
Step 61/179 : RUN if [ ${INSTALL_XDEBUG} = true ]; then     apt-get install -y php${LARADOCK_PHP_VERSION}-xdebug &&     sed -i 's/^;//g' /etc/php/${LARADOCK_PHP_VERSION}/cli/conf.d/20-xdebug.ini &&     echo "alias phpunit='php -dzend_extension=xdebug.so /var/www/vendor/bin/phpunit'" >> ~/.bashrc ;fi
 ---> Running in 2895b9d82cec
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  php-xdebug
0 upgraded, 1 newly installed, 0 to remove and 110 not upgraded.
Need to get 915 kB of archives.
After this operation, 5,325 kB of additional disk space will be used.
Err:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php-xdebug amd64 2.6.0+2.5.5-1+ubuntu16.04.1+deb.sury.org+1
  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/x/xdebug/php-xdebug_2.6.0+2.5.5-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_XDEBUG} = true ]; then     apt-get install -y php${LARADOCK_PHP_VERSION}-xdebug &&     sed -i 's/^;//g' /etc/php/${LARADOCK_PHP_VERSION}/cli/conf.d/20-xdebug.ini &&     echo "alias phpunit='php -dzend_extension=xdebug.so /var/www/vendor/bin/phpunit'" >> ~/.bashrc ;fi' returned a non-zero code: 100

```

### PR DESCRIPTION
**Pull request by manierim**
##### I completed the 3 steps below:

- [x] I've read the [Contribution Guide](http://laradock.io/contributing).
- [x] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by IgArI0K** [comment]
Can we have this PR merged as below issues appears if above update is not included

image

**Comment by bestlong** [comment]
please use `docker-compose build --no-cache workspace`

**Comment by IgArI0K** [comment]
Thanks @bestlong , for now manually added to to be able to build.

Next issues is that i cannot seem to connect xdebug with phpstorm :(

**Comment by vitomeuli** [comment]
I added  an `apt-get update` before the real install in the workspace Dockerfile, as suggested in #1865

**Pull request closed without merging**
