### PR TITLE
add swoole extension config

### PR DESCRIPTION
**Pull request by wxb**
add swoole extension
Swoole is an event-driven asynchronous & concurrent networking communication framework with high performance written only in C for PHP.

 [what's swoole?](https://git.oschina.net/swoole/swoole)

### CODE REVIEW

**Comment by a-h-abid** [comment]
You missed to include build args in docker-compose.yml file...

**Comment by wxb** [comment]
@a-h-abid 
no, swoole is a C extension; so don't need to configure docker-compose.yml

**Comment by a-h-abid** [comment]
@wxb Your env file setting name is `PHP_FPM_INSTALL_SWOOLE` and in dockerfile you are looking for argument `INSTALL_SWOOLE`. As of now, the argument value will always be *false* since it is not linked with the env setting. You connect these in docker-compose.yml. Like below:

```
php-fpm:
  build:
    context: ./php-fpm
    args:
      ....
      - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
      - INSTALL_GHOSTSCRIPT=${PHP_FPM_INSTALL_GHOSTSCRIPT}
      - INSTALL_LDAP=${PHP_FPM_INSTALL_LDAP}
      - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
```

**Comment by wxb** [comment]
@a-h-abid 
sorry, I am wrong, you said is right。 👍

**Comment by wxb** [comment]
@a-h-abid 
I add, [#943](https://github.com/laradock/laradock/pull/943)

**Comment by a-h-abid** [comment]
thanx

**Pull request merged**
