### PR TITLE
PostGIS - 1)Add PostGIS VERSION and 2)add option to install 'pgsql-http' ext

### PR DESCRIPTION
**Pull request by vlauciani**
1. Add Postgres version to install (use `POSTGRES_VERSION` variable)
2. Add variable (`POSTGIS_INSTALL_PGSQL_HTTP_FOR_POSTGIS13`) to install `pgsql-http` (https://github.com/pramsey/pgsql-http.git) extension.

Issue: https://github.com/laradock/laradock/issues/3115

### CODE REVIEW

**Comment by vlauciani** [comment]
Please, merge! 🙏

It is important to have PostGIS version equal to Postgres (`POSTGRES_VERSION`)!

**Comment by modder2** [comment]
@vlauciani You have one **bug** in your code.
`postgres` and `postgis/postgis` have **different tags**,
 and use of this:
```
ARG POSTGRES_VERSION=latest
FROM postgis/postgis:${POSTGRES_VERSION}
```
results in an error, because `POSTGRES_VERSION` equals "alpine" in `.env`, but **no tag "alpine"** for `postgis/postgis` image.
https://registry.hub.docker.com/r/postgis/postgis/tags?name=alpine

You should define a new one argument `POSTGIS_VERSION=latest` in `.env` and use it in `postgres-postgis/Dockerfile`:
```
ARG POSTGIS_VERSION=latest
FROM postgis/postgis:${POSTGIS_VERSION}
```

@bestlong please pay attention.

**Comment by vlauciani** [comment]
Ok, thank you @modder2 , I'll fix it.

**Comment by vlauciani** [comment]
@modder2 please, check di PR:
- https://github.com/laradock/laradock/pull/3131

Cc: @bestlong

**Pull request merged**
