### PR TITLE
Added support for OCI8 extension in workspace and php-fpm containers.

### PR DESCRIPTION
**Pull request by jzonta**
This PR provides OCI8 extension supports in workspace and php-fpm containers.
Suport - PHP 5.6, 7.0, 7.1, 7.2 and 7.3

Related issue: Oracle Interface or oci8 support by default #1274

##### I completed the 3 steps below:

- [x] I've read the [Contribution Guide](http://laradock.io/contributing).
- [ ] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by bestlong** [comment]
Hi @jzonta 
php-worker can it also be supported?

**Comment by jzonta** [comment]
> Hi @jzonta
> php-worker can it also be supported?

I have not tested for php-worker, I will test, but this year I am working hard. Soon I will test.

**Comment by jzonta** [comment]
@bestlong I tried to install the OCI8 extension on php-worker, but the alpine image didn't work. I searched the internet for solutions, but all indicate the installation of a non-alpine image. So for now, OCI8 extension doesn't work in php-worker

**Comment by bestlong** [comment]
@jzonta It doesn't matter, i merge first, and wait for someone to deal with

**Pull request merged**
