### PR TITLE
Integrating docker sync

### PR DESCRIPTION
**Pull request by arianacosta**
I think Laradock is a fantastic project, unfortunately, after setting it up I realized it that was performing very poorly on OS X. In my benchmarks, it is slower than MAMP and even Vagrant. Loading a page would take ~1.2 seconds, which makes laradock less than ideal for development on a Mac.

Looking for solutions, I came across [docker-sync](https://github.com/EugenMayer/docker-sync) which processed the same page in about ~180ms (6X faster than vanilla laradock). However, setting it up was very cumbersome and took a lot of time, because of the lack of good documentation, and several problems with user permissions and syncing methods. For that reason, I have decided to integrate it with Laradock and give back to this awesome community. 

In short, these are some of the features of my contribution:

- Provides an easy out-of-the-box solution to setup docker-sync.
- Does not affect previous laradock setups.
- Enables laradock to run with or without docker-sync on demand.
- Incorporates an optional `sync.sh` to easily install, start and stop laradock with docker-sync.
- Maintains configurations dry.

All the details are in the documentation, but the usage is simple, just run:

```
./sync.sh install
./sync.sh up nginx mysql
./sync.sh down
```
These are the available options:
```
   install		 Installs docker-sync gem on the host machine.
   up [services]	 Starts docker-sync and runs docker compose.
   down			 Stops containers and docker-sync.
   bash			 Opens bash on the workspace.
   sync			 Manually triggers the synchronization of files.
   clean		 Removes all files from docker-sync.
```
##### Make sure you completed the basic 3 steps below:

- [x] I've read the simple [Contribution Guide](http://laradock.io/contributing).
- [x] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by Mahmoudz** [comment]
@arianacosta looks pretty cool. Thanks for the contribution. 

I think the docs aren't accurate I think it should be `./sync.sh docker-sync-stack up` instead `docker-sync-stack start`!

**Comment by arianacosta** [comment]
Hi! Thanks for the quick reply. I tried using `docker-sync-stack up`, but it doesn't allow you to specify the services as arguments as the usual `docker-compose up <services>`. In my tests, it would just start all services. So, I wanted to keep it as flexible and as close as possible to the regular `docker-compose` command which allows people to run only the containers they need at that moment. What do you think it should be?

**Comment by Mahmoudz** [comment]
@arianacosta totally agree on keeping the commands similar to docker. My concern was with the missing `./sync.sh ` and when I tried the up command it didn't work! Maybe I did something wrong. Could you please add to the docs, steps like this:

1. run command xxx
2. do this
3. do that..

With some details on what's going on behind the scene.

Thanks,

**Comment by arianacosta** [comment]
@Mahmoudz No problem, I will improve the documentation even more, and add the info of the commands without the `.sync.sh` helper. Also, if you could provide the error that you are seeing, that would be great.

Thank you

**Comment by realshadow** [comment]
@arianacosta This might not be good place to ask this. But I don't see any performance improvment whatsoever. Tried all strategies, request time fluctuates from 4-6 seconds - same as vanilla laradock. Any idea what could be the cause? I can get down to 500ms with dinghy

**Comment by hmaurer** [comment]
Unless I am mistaken docker-compose should be started using a flag (or env var) to load `docker-compose.sync.yml` instead of `docker-compose.dev.yml`? Using `./sync.sh up` did not work for me. After some googling I tried `docker-compose -f docker-compose.yml -f docker-compose.sync.yml up`, which seems to work perfectly. Am I missing something?

**Pull request merged**
