### PR TITLE
Install php-redis for laravel-horizon

### PR DESCRIPTION
**Pull request by NetBT**
##### I completed the 3 steps below:

- [x] I've read the [Contribution Guide](http://laradock.io/contributing).
- [x] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by vlauciani** [comment]
Hi

Why you need to install Redis into the laravel-horizon docker image?

**Comment by NetBT** [comment]
When I run the laraval-horizon service, the service will report an error. I checked the run log, which showed that phpredis was missing

**Comment by vlauciani** [comment]
Thank you for your answer.

Could you tell me which log are you looking for?

**Comment by NetBT** [comment]
Laravel console log

**Comment by vlauciani** [comment]
Which version of Laravel are you using? 

In my 5.7 I'm using Laravel-Horizon from 5months and I can't find this error.

**Comment by NetBT** [comment]
Laravel 5.5
The database config is like this
`'redis'=>[
'client'=>'phpredis' // not predis
]`
[Laravel redis config](https://laravel.com/docs/5.5/redis#phpredis)

**Comment by vlauciani** [comment]
ok thank you for the explanation!

**Comment by bestlong** [comment]
sorry duplicate https://github.com/laradock/laradock/pull/2286

**Pull request closed without merging**
