### PR TITLE
Change command about enter workspace container.

### PR DESCRIPTION
**Pull request by appleboy**

### CODE REVIEW

**Comment by AminMkh** [comment]
one note about ``` run ``` instead of ```exec```, is that ``` run ``` will fire up another container, isolated from the one already running. Which might be okay except for a bit couple of reasons why not to:

1- Since you'll be in the bash of another container, you can't reload configurations or restart nginx/mysql, check logs ...etc.

```
docker-compose exec nginx bash
root@a00d4f016a92:/# service nginx reload
Reloading nginx: nginx.
```

```
docker-compose run nginx bash
Starting laradock_application_1
root@d9b209ec4c10:/# service nignx reload
nignx: unrecognized service
```
2- Overhead of another container, 
```
docker-compose run workspace bash
```

is basically 
```
docker run -it laradock_workspace bash
```

**Comment by appleboy** [comment]
@AminMkh You are right. I will improve the readme and send another PR.

cc @Mahmoudz

**Comment by appleboy** [comment]
@Mahmoudz Do you have any opinion?

**Comment by Kauhat** [comment]
Just a heads up for Windows, `docker-compose run workspace bash` doesn't seem to work properly yet. E.g:

```
ERROR: Interactive mode is not yet supported on Windows.
Please pass the -d flag when using `docker-compose run`.
```

Passing the `-d` flag will run the container in the background, which isn't what we want in this case. For that reason I'd recommend keeping the existing commands in the readme for Windows users.

```
λ docker -v & docker-compose -v
Docker version 1.12.0-rc2, build 906eacd, experimental
docker-compose version 1.8.0-rc1, build 9bf6bc6
```

**Comment by Mahmoudz** [comment]
@AminMkh that's absolutely right, when I tested this I only typed `docker-compose ps` and it didn't showed me that a new container was created. After your comment I typed `docker ps -a` and I've seen the duplicated containers. That's definitely a problem as you mentioned, no one would be interested in building new containers this way. Thanks for noticing that.

@appleboy I will override those changes with a new commit since I did some updates on top of yours in a separate commit directly to master so reverting this back won't remove it all.

Thanks you guys

**Pull request merged**
