### PR TITLE
Add PHP 7.2 support and fix issues on 5.6-7.0-7.1 versions

### PR DESCRIPTION
**Pull request by desaroger**
##### I completed the 3 steps below:

- [x] I've read the [Contribution Guide](http://laradock.io/contributing).
- [x] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

Hi!
I know there is another PR wich adds 7.2 support (I think it is only for php-fpm), but it is not merged yet (and seems to have some issue) with and I needed 7.2 support **today**, so I ended up making my own.
I am sure I need something more than this, because the other PR has more changes than mine.

I strictly followed the contributing guide, tested everything, built everything without cache and tested with a real world app, a symfony 4 project, and everything worked fine. My main doubt is if php 7.2 has enough usage to be the default version for laradock. I am not sure, if not please tell me and I will change it.

Thanks! Any help will be welcome :D

PS: I checked the documentation point but (I think) there was nothing to put there. I look for 'php 7' but didn't found nothing, so I assumed there was nothing about the PHP version there. If I am wrong please tell me

### CODE REVIEW

**Comment by desaroger** [comment]
Some tests failed on php 5.6, I am looking the travis output to check what is going on, as I didn't change anything of 5.6 version.

**Comment by desaroger** [comment]
Mmm this failed travis cases fails also in master to me :/

**Comment by desaroger** [comment]
I finally make everything work. I found some issues on master branch with another PHP versions that made travis don't pass the tests (on master) and I think I solved everything. I found some other problems related to PHP version, as sometimes the installation of a library forced the installation of an incorrect PHP version, so I added a check on the end of all php related Dockerfiles to make sure that at the end we have the PHP version we expect to have.

My only concern is that I need to downgrade the Swoole version on PHP 5.6 to make it work.

**Comment by taufek** [comment]
This is great work!

**Comment by desaroger** [comment]
@Mahmoudz Is there anything else I have to do to make you merge this PR?

**Comment by desaroger** [comment]
Sorry @bestlong, I forgot to add the new test cases to the travis.yml! Thanks for your changes. I added some fixes to pass all the tests

**Comment by bestlong** [comment]
Also fix #1379

**Pull request merged**
