### PR TITLE
add   restart: always for all service

### PR DESCRIPTION
**Pull request by AliEbrahimpour**
## Description
i add restart: always for all service because while server restart all service not start automaticly

## Types of Changes

- [] Bug fix

### CODE REVIEW

**Comment by AliEbrahimpour** [comment]
hi every one add restart fot all service while server restart then all container auto stated

**Comment by AliEbrahimpour** [comment]
@appleboy 
@sodabrew 
@tjlytle 
@samdark

**Comment by AliEbrahimpour** [comment]
I added this topic a long time ago, and no one has reviewed it.

**Comment by AliEbrahimpour** [comment]
i also add  time zone for php-fpm

**Comment by AliEbrahimpour** [comment]
i have also add time zone for php worker
@bestlong

**Comment by w1lldone** [comment]
Hi @bestlong,

I don’t think this was the best approach. Now I have to manually stop all my active containers before shutting down my PC, or they’ll automatically start when I turn it back on.

**Comment by AliEbrahimpour** [comment]
> Hi @bestlong,
> 
> I don’t think this was the best approach. Now I have to manually stop all my active containers before shutting down my PC, or they’ll automatically start when I turn it back on.

Dear friend, I am talking about the production and not the personal system where you have the opportunity to turn off the containers and when the server is turned off, it will not ask you.

**Comment by w1lldone** [comment]
I understand that you use Laradock on your production server. However, Laradock may not be the most suitable option for production environments by itself. The Laradock repository states that it is a "Full PHP development environment for Docker." Additionally, the documentation recommends creating your own docker-compose.yml file specifically tailored for production environments (https://laradock.io/documentation/#prepare-laradock-for-production)

For this reason, I believe your current method is not the best approach. You should consider creating a custom docker-compose.yml file tailored for your production needs.

**Comment by AliEbrahimpour** [comment]
I think that since you are working with it on your own system, you can delete those items so that this system is suitable for production before it is run again on your system.

**Pull request merged**
