### PR TITLE
Fixing environment in docker-compose file

### PR DESCRIPTION
**Pull request by zeroc0d3**
```
> docker-compose version
docker-compose version 1.11.2, build dfed245
docker-py version: 2.1.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

> docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/am
```

### CODE REVIEW

**Comment by appleboy** [comment]
conflicts.

**Comment by zeroc0d3** [comment]
@appleboy, Solved...

**Comment by alchimik** [comment]
Why did you replace 4 spaces by 2?

**Comment by zeroc0d3** [comment]
@alchimik, i'm using standard "spaces" in yaml configuration file

**References:** 
1) [Official](https://docs.docker.com/compose/environment-variables/#setting-environment-variables-in-containers)
2) [Other](http://docker-map.readthedocs.io/en/stable/guide/containers/yaml.html)

**Comment by thorerik** [comment]
The standard is on a project level, nither of your references specify and recommendation on the indentation, yaml only require consistency, which was already present.

**Comment by Mahmoudz** [comment]
Yep we need to resolve the conflict here before merging. @zeroc0d3 could you!

**Comment by zeroc0d3** [comment]
@Mahmoudz, all done... conflict resolved

**Comment by Mahmoudz** [comment]
@zeroc0d3 maybe something caused another conflicts today can resolve it again.

**Comment by zeroc0d3** [comment]
@Mahmoudz, all done...

**Comment by zeroc0d3** [comment]
@Mahmoudz perhaps need to merge into master, so would never conflict

**Comment by Mahmoudz** [comment]
now the conflict is because of `APPLICATION=../project/` I just noticed it was missing and I add it, before trying to merge the PR's since there wasn't a specific PR to solve it. If you fix this I should be able to merge it. Sorry for that delay.

**Comment by zeroc0d3** [comment]
ok @Mahmoudz, we're using `APPLICATION=../` now

**Comment by alchimik** [comment]
@Mahmoudz @zeroc0d3 
image
Is it so hard to see the diff before merge?

@zeroc0d3
What fixes this commit (pull)? indent_size? Now the indentation is really broken. 2 and 4 spaces in one file (docker-compose.yml)
image
ridiculous

"Fixing environment in docker-compose file" - What was wrong with them?

**Comment by zeroc0d3** [comment]
@alchimik, more than two times conflict resolved

**Pull request merged**
