### PR TITLE
Added service container for Selenium standalone with Chrome

### LINKED ISSUE #356: Idea: Add support for Selenium containers (for PHPUnit, Behat)
Hi,

[Behat](https://github.com/Behat/Behat) is a very popular BDD testing framework for PHP that has relevance in the Laravel community thanks to the [Laracasts series on it](https://laracasts.com/lessons/laravel-5-and-behat-bffs). 

Although Behat is great for testing static HTML and PHP code, it cannot test Javascript frontend components without [using a browser emulator](http://mink.behat.org/en/latest/drivers/selenium2.html), such as [Selenium](http://www.seleniumhq.org/). Selenium is also [supported in PHPUnit](https://phpunit.de/manual/4.8/en/selenium.html) as well, giving the developer the option to use it if they choose to.

With Javascript frontend frameworks being so prevalent these days, it might be useful to have the option to run a Selenium server in a container in Laradock so you have the capability of testing Javascript frontend components. 

There appears to be existing Docker repository for Selenium at [SeleniumHQ/docker-selenium](https://github.com/SeleniumHQ/docker-selenium), but I am not very experienced with configuring Docker Compose and adding new containers.

If there is support for this and I can figure out how to add containers to Docker Compose, I wouldn't mind  doing this as a PR. Let me know what you think.

### PR DESCRIPTION
**Pull request by edmundluong**
Resolves #356 

Added Selenium using the official Selenium docker images from https://github.com/SeleniumHQ/docker-selenium

The Selenium server is served on port 4444

### CODE REVIEW

**Comment by appleboy** [comment]
Can you update the README file?

**Comment by edmundluong** [comment]
@appleboy Updated, thanks

**Comment by philtrep** [comment]
@edmundluong thanks for your contribution!

**Comment by symbios-zi** [comment]
@edmundluong Hello. Do you use it for codeception? 
I am trying to configure it for use acceptance tests. It requires selenium web driver or phantomJS.

But the problem is website url which unavailable inside selenium container.

**Comment by chkm8** [comment]
Hi, im trying to integrate browser testing with dusk and selenium, when I run php artisan dusk , all my test are passing but I cant see the browser being loaded or open? 

Steps: (scripts below are excuted inside workspace - docker-compose exec workspace bash)
1-docker-compose up -d apache2 selenium
2-added/setup dusk (php artisan dusk:install)
3-created browser test
4-php artisan dusk
->My sample regression does succeed but I can't see the browser being tested.
--visited the selenium url: http://localhost:4444/wd/hub
--I can only see a session menu

What am I missing here? Thanks.

**Pull request merged**
