### PR TITLE
Various readme typo fixes/improvements

### PR DESCRIPTION
**Pull request by ngyikp**

### CODE REVIEW

**Comment by appleboy** [comment]
@Mahmoudz Please help to review `LaraDock` -> `Laradock`

**Comment by scoutman57** [comment]
DO NOT approve this PR. LaraDock is correct and should NOT be changed to "Laradock". There are some other spelling and grammar issues that was corrected that should still be fixed in a new PR.

**Comment by ngyikp** [comment]
Best for me to send a PR without the LaraDock/Laradock normalization instead?

Or I could change it to LaraDock as requested.

**Comment by appleboy** [comment]
@ngyikp Please revert ` LaraDock/Laradock normalization`

**Comment by appleboy** [comment]
LGTM

**Pull request merged**
