### PR TITLE
update Workspace port to 2222

### PR DESCRIPTION
**Pull request by dilone**
i was having problems with the port 22, is already in use on my PC.

### CODE REVIEW

**Comment by philtrep** [comment]
@dilone Thanks for your contribution.

Do you have a reasoning behind using the port `2222` instead?

If it's only because of conflict, I don't think we should use the alternate ssh port by default, `22` is standard and if we follow the config for our other images we should be using standard ports for forwarding.

That being said, if you've had an issue with conflicting ports maybe we can address it in the debugging section of the documentation?

**Comment by dilone** [comment]
i have ssh server running on my Fedora, taking the port 22 by default, changing the map to the 2222 works great for me, all the command runs the same way, i just think is good addition to the project.

**Comment by philtrep** [comment]
@Mahmoudz what do you think? `22` is development centric since if you ssh into a server the `22` port is probably already taken but I have seen configs using `2222`...

**Comment by Mahmoudz** [comment]
@philtrep @dilone it makes sense, seems changing the default `22` would solve it but I'm not sure if it will cause troubles to the current users!! I'll leave it for you guys to decide.

**Comment by philtrep** [comment]
Okay I'll merge this in since it does make sense that you might already have the port `22` used by ssh on your host machine, we'll revise if we get too many issues about this.

Thanks again for your contribution @dilone :)

**Comment by Mahmoudz** [comment]
should we mention that somewhere in the docs!?

**Comment by philtrep** [comment]
@Mahmoudz good point! I haven't seen any mention of actual `ssh` (only `exec`) in the doc but we should indeed add a mention.

**Comment by Mahmoudz** [comment]
@philtrep thanksss

**Pull request merged**
