### PR TITLE
Fix bug installing "IMAGEMAGICK" into "php-fpm" docker image

### PR DESCRIPTION
**Pull request by vlauciani**
Fix bug installing _IMAGEMAGICK_ into _php-fpm_ docker image.

Issue:
- https://github.com/laradock/laradock/issues/2856
- https://github.com/laradock/laradock/issues/2865

### CODE REVIEW

**Comment by bestlong** [comment]
this is cache issue
try `docker-compose build --no-cache --pull php-fpm`

**Comment by vlauciani** [comment]
I tried your solution, but the error is the same:
```
$ docker-compose build --no-cache --pull php-fpm
. . .
. . .
Get:170 http://deb.debian.org/debian buster/main amd64 libtool all 2.4.6-9 [547 kB]
Get:171 http://deb.debian.org/debian buster/main amd64 netpbm amd64 2:10.0-15.3+b2 [1029 kB]
Fetched 68.3 MB in 7s (9982 kB/s)
E: Failed to fetch http://deb.debian.org/debian/pool/main/c/cairo/libcairo2_1.16.0-4_amd64.deb  404  Not Found [IP: 151.101.242.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/c/cairo/libcairo-gobject2_1.16.0-4_amd64.deb  404  Not Found [IP: 151.101.242.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/c/cairo/libcairo-script-interpreter2_1.16.0-4_amd64.deb  404  Not Found [IP: 151.101.242.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/c/cairo/libcairo2-dev_1.16.0-4_amd64.deb  404  Not Found [IP: 151.101.242.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_IMAGEMAGICK} = true ]; then     apt-get install -y libmagickwand-dev imagemagick &&     if [ $(php -r "echo PHP_MAJOR_VERSION;") = "8" ]; then       apt-get install -y git &&       cd /tmp &&       if [ ${IMAGEMAGICK_VERSION} = "latest" ]; then         git clone https://github.com/Imagick/imagick;       else         git clone --branch ${IMAGEMAGICK_VERSION} https://github.com/Imagick/imagick;       fi &&       cd imagick &&       phpize &&       ./configure &&       make &&       make install &&       rm -r /tmp/imagick;     else       pecl install imagick;     fi &&     docker-php-ext-enable imagick ;fi' returned a non-zero code: 100
```

**Comment by bestlong** [comment]
merged is my mistake.
fetch fail some time is network problem.

**Comment by vlauciani** [comment]
Please, consider to merge; the problem persists:
- https://github.com/laradock/laradock/issues/2856#issuecomment-809446445

**Pull request merged**
