### PR TITLE
Add the ability to install ffmpeg on Laravel Horizon container

### PR DESCRIPTION
**Pull request by ludo237**
##### I completed the 3 steps below:

- [x] I've read the [Contribution Guide](http://laradock.io/contributing).
- [ ] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

## Introduction
Inspired by this [pull request](https://github.com/laradock/laradock/pull/2118) I've updated the Laravel Horizon Dockerfile to install `ffmpeg`.

## Problem to solve
The main issue is that if you don't use `php-worker`, but you use horizon as a queue manager, and you need to process jobs that need `ffmpeg` you won't be able to process them because ffmpeg is not available inside the laravel-horizon container

Does this pull request have breaking changes? No because the `env-example` contains the parameter set to **false** by default thus the update won't break any old setup

The documentation has not been updated since I was unable to find a section dedicated to laravel horizon.

### CODE REVIEW

**Comment by cloudberrystory** [comment]
This fix solved my problem.
Thank you so much!)

**Comment by cloudberrystory** [comment]
Also if you wanna use ffmpeg you should add non root user into laravel-horizon.
If you dont do that, all your files and paths will be created by root user.
You can do it like in php-worker.

laravel-horizon Dockerfile
image

laravel-horizon args docker-compose.yml
image

**Comment by ludo237** [comment]
Good catch, I'll fix the PR asap

**Comment by ludo237** [comment]
@cloudberrystory thanks for the updates, I've fixed my PR.

Also ping to @Mahmoudz for review and @bestlong

**Pull request merged**
