### PR TITLE
bugfix weaver conf

### LINKED ISSUE #3063: window10 cmd 执行docker-compose up -d nginx mysql
unexpected character "-" in variable name near "-S\nWEAVER_MAX_WORKERS=10\nWEAVER_MAX_CONVERSION_QUEUE=50\nWEAVER_WORKER_TIMEOUT=90\nWEAVER_CONVERSION_FALLBACK=false\n\n# CloudConvert\n# API key can be found: https://cloudconvert.com/use
r/profile\n# CLOUDCONVERT_API=https://api.cloudconvert.com\n# CLOUDCONVERT_KEY=\n\n# Monitoring\n# STATSD_ADDRESS=\n# STATSD_PREFIX=\n# SENTRY_DSN="

### PR DESCRIPTION
**Pull request by davidjr82**
Fix #3063

## Description
Modify values in weaver config file to use quotes.

## Motivation and Context
With the upgrade of docker it doesn't work anymore

## Types of Changes
- [x] Bug fix (non-breaking change which fixes an issue).
- [] New feature (non-breaking change which adds functionality).
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Definition of Done Checklist:
- [x] I've read the [Contribution Guide](http://laradock.io/contributing).
- [] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by dhtmdgkr123** [comment]
o0o
your Pull Request verrrrry fast...

**Comment by davidjr82** [comment]
@dhtmdgkr123 was to fix it, but I can remove it and you PR yourself if you want :)

**Comment by dhtmdgkr123** [comment]
@davidjr82 If u want remove this close this pull request

**Comment by davidjr82** [comment]
closed @dhtmdgkr123 , waiting for your PR ;)

**Comment by dhtmdgkr123** [comment]
@davidjr82 thank u :) i will PR this Issue!

**Comment by dhtmdgkr123** [comment]
@davidjr82 Open [PR](https://github.com/laradock/laradock/pull/3066) thank your consideration!

**Pull request closed without merging**
