### PR TITLE
Add dockerfile with php-fpm 7.1

### PR DESCRIPTION
**Pull request by AliveCorpse**
Merge after [php-fpm](https://github.com/laradock/php-fpm/pull/7) and need change base-image tag

### CODE REVIEW

**Comment by edmundluong** [comment]
@philtrep @Mahmoudz @appleboy 

+1 Would love to see PHP7.1 get merged into Laradock, what needs to be done to get this merged?

**Comment by philtrep** [comment]
@edmundluong We needed to merge the new laradock/php-fpm Dockerfile @AliveCorpse provided which I did 5 minutes ago, now we only have to do the proper modifications in this PR and we are good to go!

Also thanks for the bump.

**Comment by alexey-m-ukolov** [comment]
@philtrep what exactly needs to be done?

**Comment by philtrep** [comment]
@alexey-m-ukolov we need to push the laradock/php-fpm image to the Dockerhub. I can't do that since I don't have the creds for it, could you do it @Mahmoudz when you have some time?

Once that's done we can update the tag in this dockerfile then Ill merge the PR.

**Comment by edmundluong** [comment]
@philtrep @Mahmoudz Bump. Would really love to see this get merged in.

**Comment by jakubkratina** [comment]
Can I help you to merge this? I would love to use PHP 7.1 :)

**Comment by philtrep** [comment]
@Mahmoudz tried to push the image to the Dockerhub but there seems to be errors in it according to #539  @mikeerickson @edmundluong @jakubkratina  those need to be resolved and I simply don't have time to take care of this at the moment so if you guys have the solution do create a PR, @Mahmoudz will push to the Dockerhub again, we'll be able to merge this in and we'll finally get that PHP7.1 running for LaraDock.

**Comment by mikeerickson** [comment]
@philtrep I will have a look at this item and get issue(s) resolved so we can close this.  I am sure PHP 7.1 request will increase over time (and I could use it as well)

**Pull request merged**
