### PR TITLE
setup auth plugin to native password by default

### PR DESCRIPTION
**Pull request by Yiidiir**
Access denied for user defined in .env in MySQL 8
#1694

##### I completed the 3 steps below:

- [*] I've read the [Contribution Guide](http://laradock.io/contributing).
- [*] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [*] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by lanphan** [comment]
Hi,
This should not be mandatory to change default auth to the old one. Please read my comment here https://github.com/laradock/laradock/pull/2156 to see the way to enable it if you want.

**Comment by metalcamp** [comment]
Fixed in https://github.com/laradock/laradock/pull/2510.

**Comment by Yiidiir** [comment]
@lanphan how come my PR wasn't merged and then a year after someone does exactly same and gets merged?

**Comment by bestlong** [comment]
Hi @Yiidiir 
I'm sorry for this
When i deal with merge
Did not notice a duplicate situation
Say sorry again.

**Comment by Yiidiir** [comment]
No worries.

**Pull request closed without merging**
