### PR TITLE
Adding intl support to php-fpm container

### PR DESCRIPTION
**Pull request by cjmaxik**
W/o docs, sorry

http://php.net/manual/en/intro.intl.php

### CODE REVIEW

**Comment by cjmaxik** [comment]
Sure, there is one https://github.com/laradock/laradock/pull/466, but it works :)

**Comment by Mahmoudz** [comment]
@cjmaxik I closed that #466 it's been there for a long time and no one has closed it yet. Could you please solve this conflict to merge this. Thanks,

**Comment by cjmaxik** [comment]
@Mahmoudz done

**Comment by Mahmoudz** [comment]
@cjmaxik Thank,

**Pull request merged**
