### PR TITLE
Update startup

### PR DESCRIPTION
**Pull request by Blaasvis**
Fix creating user on startup;

### CODE REVIEW

**Comment by Blaasvis** [comment]
just fixed it, sorry about that

**Comment by philtrep** [comment]
@Blaasvis no problem, could you please squash commits? Everything looks good on my end but since this affects a few people I'll wait a few hours before merging this in so people have time to review it.

**Comment by Blaasvis** [comment]
Allright done, never knew that was possible very nice.

**Comment by philtrep** [comment]
@Blaasvis You didn't keep the change for `ONMYSQL_DATABASE` ;)

**Comment by Blaasvis** [comment]
Grumble :P well it is all new to me this squashing but now it get it, need to use S to squash not to delete the line... RTFM...

**Comment by ELD** [comment]
I've had a chance to check it out and test it. Works perfectly fine for me. Looks good! 👍

**Comment by philtrep** [comment]
@Blaasvis Thank you for your contribution 😄

**Pull request merged**
