### PR TITLE
Graphviz support

### PR DESCRIPTION
**Pull request by juniorrosul**
Graphviz support in workspace

Issue #1003

### CODE REVIEW

**Comment by bestlong** [comment]
Hi @juniorrosul 
why remove mysql/docker-entrypoint-initdb.d/createdb.sql.example ?

**Comment by juniorrosul** [comment]
Hi @bestlong,

I made some mess, let me fix that.

**Comment by juniorrosul** [comment]
Hey @Mahmoudz I need some help here, those errors on build are happen on another dependency, i have to create a new issue to discuss that and create a pull request for this only? Or can I apply the correction in this PR?

**Comment by bestlong** [comment]
Hi @juniorrosul 
can you fix mysql/docker-entrypoint-initdb.d/createdb.sql.example first?
then i well merge.

**Comment by bestlong** [comment]
i think rename nginx/sites/default is not good idea. is need more config step to use laradock.
What do you think?

**Pull request merged**
