### PR TITLE
change application source #397

### PR DESCRIPTION
**Pull request by mouyong**
# fix a problem--#397, change application source from dl-cdn.alpinelinux.org to aliyun source.

### CODE REVIEW

**Comment by mikeerickson** [comment]
@mouyong thank you for your contribution.  Seemingly straight forward.  Did you perform this on Windows?  We are trying to make sure each PR gets tested on Windows as it can be "funky" 😊

**Comment by mouyong** [comment]
@mikeerickson yes, on windows 10 pc.

**Comment by fedemotta** [comment]
@philtrep This is generating issues, because for example this file is taking ages to download http://mirrors.aliyun.com/alpine/v3.4/main/x86_64/APKINDEX.tar. I rollbacked the changes and it is working fine

**Comment by philtrep** [comment]
@fedemotta I see, would you care to elaborate? The issue this fixed was quite common I believe so I'm not too keen on rolling back the changes...

**Comment by fedemotta** [comment]
@philtrep When I tried to rebuild the containers it takes several hours to finish because some aliyun.com links were taking ages to download. 
So strange that noone else notice this issue. I found the issue first rebuilding inside an AWS ec2 in Virginia. In my local enviroment was happening too. I am from Argentina.

The cdn is working now. It seems that it was down when the issue raises. This PR was a temporary fix and I think it shouldnt been merged.

See the speed download of each link:
http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
vs.
http://mirrors.aliyun.com/alpine/v3.4/main/x86_64/APKINDEX.tar.gz

Could you reproduce the issue? Should I open a new issue about this?

Cheers

**Comment by mouyong** [comment]
@fedemotta @philtrep if you in china , i think you can accept it,
> http://mirrors.aliyun.com/alpine/v3.4/main/x86_64/APKINDEX.tar.gz

if you no in china , i think you can delete it .

and i have some suggestion.

> http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz

doesn't exists some file. so ,have sometime , in china ,it can throw error.
so when i change sourse ,it can work.

**Comment by fedemotta** [comment]
@mouyong  @philtrep So you think it is possible to implement something using ENV variables, to easily switch the url? Do you think that the china mirror should be the default?

**Comment by mouyong** [comment]
no,i dont think, and i dont know do it better ,the project have some chinainese ues.if you have a better fanction. you can propose ,let us help more people. and i also can accept your suggestion and learn it. how do you think? @fedemotta @philtrep

**Comment by mouyong** [comment]
I believe that everyone wants to be better and help us to finish our work better. If you have any good advice, I think you can propose it. how do you think?

**Pull request merged**
