### PR TITLE
Add Node Version Manager (nvm)

### PR DESCRIPTION
**Pull request by appleboy**
Hi @Mahmoudz @Kauhat

`Workspace` container support `nvm` tool now. Please help to verify `Dockerfile` again. Thanks.

screen shot 2016-06-22 at 9 32 03 am

screen shot 2016-06-22 at 9 32 30 am

Fixed issue: #106, #100

Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

### CODE REVIEW

**Comment by Kauhat** [comment]
Verified working for me using Docker for Windows version 1.12.0-rc2.

```
root@81f00ca78097:/var/www/laravel# node -v
v6.2.2
root@81f00ca78097:/var/www/laravel# npm -v
3.9.5
root@81f00ca78097:/var/www/laravel# gulp -v
[08:48:57] CLI version 3.9.1
[08:48:57] Local version 3.9.1
root@81f00ca78097:/var/www/laravel# bower -v
1.7.9
```

Thanks!

**Comment by fanly** [comment]
but npm install very slow...

**Comment by canfone** [comment]
How to install npm and node to your workspace container?

**Comment by IsiRoca** [comment]
@canfone Go to your .env file and change the "WORKSPACE_INSTALL_NODE" value in WORKSPACE section:

WORKSPACE_INSTALL_NODE=true

**Pull request merged**
