### PR TITLE
fix 404 not found with nginx

### LINKED ISSUE #1589: nginx - 404 Not Found
### Info:
- Docker version (`Docker version 18.05.0-ce`): 
- Laradock commit (`ad316bab50e98edf578d9c9c9500b7dc1a9b4dfc`): 
- System info (Linux): 
- System info disto/version: Ubuntu/18.04/bionic

### Issue:

Can not find Nginx page

### Expected behavior:

When you type localhost the Nginx page appears

### Reproduce:

sudo docker-compose up -d nginx mysql

Starting laradock_workspace_1 ... done
Starting laradock_mysql_1 ... done
Starting laradock_php-fpm_1 ... done
Recreating laradock_nginx_1 ... done

sudo docker-compose ps

Name Command State Ports 
--------------------------------------------------------------------------------
laradock_mysql_1 docker-entrypoint.sh Exit 1 
mysqld 
laradock_nginx_1 nginx Up 0.0.0.0:443->443/tcp, 
0.0.0.0:80->80/tcp 
laradock_php-fpm_1 docker-php-entrypoint Up 9000/tcp 
php-fpm 
laradock_phpmyadmin_1 /run.sh phpmyadmin Exit 0 
laradock_workspace_1 /sbin/my_init Up 0.0.0.0:2222->22/tcp

It was supposed to be okay :(

P.S: I do not have Apache on my machine

### PR DESCRIPTION
**Pull request by appleboy**
fix #1589 and ref #86

## Project Folder Structure

```
├── laradock
└── www
```

Please make sure that `public` folder of Laravel project in `www`

## Modified `laradock/.env`

```yml
APP_CODE_PATH_HOST=../www
```

## Copy nginx config

```sh
cp -r nginx/sites/laravel.conf.example nginx/sites/laravel.test.conf
```

Add `laravle.test` in `/etc/hosts`

```
127.0.0.1 laravel.test
```

## open your browser

open http://laravel.test or you can change the hostname to http://localhost

### CODE REVIEW

**Comment by appleboy** [comment]
@Mahmoudz  @bestlong any feedbacks?

**Comment by bestlong** [comment]
Suggestions to follow Multiple Projects folder structure:

no need edit .env config file.

when `www` folder is a laravel project

`cp -r nginx/sites/laravel.conf.example nginx/sites/www.test.conf`

edit nginx/sites/www.test.conf

```
server_name www.test
root /var/www/www/public
```

Add www.test in /etc/hosts
```
127.0.0.1 www.test
```

**Comment by appleboy** [comment]
I try to install Laradock for a beginner.

```
your_laravel_folder/
└── ...
└── ...
└── laradock
```

Don't modify the `laradock/.env` file

```
# Point to the path of your applications code on your host
APP_CODE_PATH_HOST=../
```

copy the default conf for nginx container. 

```
cp -r nginx/sites/laravel.conf.example nginx/sites/laravel.test.conf
```

Add laravle.test in `/etc/hosts`

```
127.0.0.1 laravel.test
```

Start the container:

```
docker-compose up -d nginx mariradb
```

Finally, you will get the 404 not found in the browser since you forgot to change the setting of root dir

```diff
- /var/www/laravel/public
+ /var/www/public
```

I think it will take a lot of time to find the root cause for a beginner.

**Comment by bestlong** [comment]
for a beginner start ref https://laradock.io/introduction/#quick-overview

`nginx/sites/default.conf` origin design is laradock in laraval project and base on `single project concept`

folder struct must is:

```bash
laravel_app_folder
├── laradock
└── public/index.php
```

if start from zero:

follow `nginx/sites/default.conf` design only need create `public/index.php`

folder struct like:

```bash
work_folder
├── laradock
└── public/index.php
```

in work_folder and run command

```bash
mkdir public
touch public/index.php
echo "<?php\necho phpinfo();\n" > public/index.php

cd laradock
cp env-example .env
docker-compose up -d nginx
```

open http://localhost

if you agree with this process, we only need update document.

**Comment by appleboy** [comment]
```diff
- root /var/www/laravel/public;
+ root /var/www/your_laravel_folder_path/public;
```

and

```diff
- 1 - Clone Laradock inside your PHP project:
+ 1 - Clone Laradock inside your Laravel project:
```

**Pull request closed without merging**
