### PR TITLE
laravel-horizon

### PR DESCRIPTION
**Pull request by frnwtr**
Added laravel horizon

### CODE REVIEW

**Comment by xlstefan** [comment]
Hi @frnwtr ,

Can you explain a bit how do I get this container to run horizon correctly?
Status of horizon when I go to /horizon says:  Inactive...
What am I missing?

**Comment by xlstefan** [comment]
Ah, just needed to rename conf file:
laravel-horizon.conf.example -> **laravel-horizon.conf**

**Comment by fridzema** [comment]
Is there any reason to install memcached in horizon container? 
Horizon only works with redis.

**Comment by xlstefan** [comment]
Exactly, it doesn't have sense to have memcached then.
Container should contain only the necessary stuff.

**Comment by vesper8** [comment]
so.. someone should make a PR to remove memcached then ?

I'm reading elsewhere that laradock has a reputation for carelessly bloating up its containers.. I guess this is what they mean

**Pull request merged**
