### PR TITLE
Ldap support

### PR DESCRIPTION
**Pull request by cabrerabywaters**
LDAP support for php 7.0

### CODE REVIEW

**Comment by Mahmoudz** [comment]
@cabrerabywaters this PR has a conflict!

**Comment by cabrerabywaters** [comment]
@Mahmoudz Just solve it...didn't realize about the change in the env config.
I also changed the GHOSTSCRIPT arg to INSTALL_GHOSTSCRIPT.
Think we should add that to the env-example_file too.

**Comment by tblancog** [comment]
@cabrerabywaters I forked the project and tried your changes since i also need ldap support for my app. Tried your changes and php still asks me for ext-ldap when i install something using composer that uses ldap.
My question is, is there any other file besides docker-compose.yml and php-fpm/Dockerfile-70 that you have changed?

**Comment by cabrerabywaters** [comment]
@tblancog Yes, the script looks for a PHP_FPM_INSTALL_LDAP env variable to be TRUE to install..so you should add 
PHP_FPM_INSTALL_LDAP=true
at the env file in the root directory of your fork.

@Mahmoudz I fixed the conflicts here!

**Comment by winfried-van-loon** [comment]
This pull request has been picked up in #933, which should add the LDAP functionality. Therefore, I'm closing this pull request. Thank you for submitting the pull request, it helped creating #933.

**Pull request closed without merging**
