### PR TITLE
Renamed env-example for IDE-compatibity; added PHP version 8.0 in the example values

### PR DESCRIPTION
**Pull request by aydin41k**
## Description
Renamed env-example to .env.example for conformity and IDE-compatibity; added PHP version 8.0 in the example values

## Motivation and Context
1. Highlights and handles the example .env file better;
2. Hints that the user can use PHP 8.0

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [] New feature (non-breaking change which adds functionality).
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Definition of Done Checklist:

- [x] I've read the [Contribution Guide](http://laradock.io/contributing).
- [] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by PavelSavushkinMix** [comment]
@aydin41k you've not update the docs.

**Comment by aydin41k** [comment]
@PavelSavushkinMix I updated the docs and a few more files.

**Comment by bestlong** [comment]
duplicate #2782

**Comment by aydin41k** [comment]
> duplicate #2782

@bestlong That one doesn't fix the reference to PHP 8.0. My PR fixes what that PR covers, plus the reference/instructions.

**Pull request merged**
