### PR TITLE
Use Travis CI for building docs & building containers

### LINKED ISSUE #735: CI integration to auto-generate the Hugo docs
Noticed the contributions to the docs became so slow, after moving to hugo... Would cool if anyone can find a good CI service to build the site automatically after each commit. This way users will only update the text in the markdown files without worrying about regenerating the site.

### PR DESCRIPTION
**Pull request by computerfr33k**
Closes #735

### CODE REVIEW

**Comment by Mahmoudz** [comment]
@computerfr33k @bestlong This seems working perfectly, all the builds are passing.

But I never saw the site actually updated!! even before merging both (docker build and hugo) in single travis.

- I commit a change to the docs
- travis start and exist with no error
- I go to the site URL and I don't see the changes!
- I tried hard reload and refreshes.. not updating.

Any hint!?

Note: no need to update

**Comment by computerfr33k** [comment]
@Mahmoudz Travis by default uploads the files to the gh-pages branch. you can switch that in the Github settings or change it in travis to point to the existing docs folder.

**Comment by Mahmoudz** [comment]
@computerfr33k I just noticed now that and came here. By "change it in travis to point to the existing docs folder" do you mean travis can update the code in the repository without submitting a pull request! or that's not possible?

**Comment by computerfr33k** [comment]
Actually I just re-read the docs for Travis GH Pages deploy, and it has to deploy to a branch. https://docs.travis-ci.com/user/deployment/pages/

But, all you will have to do for the site to change is have GH Pages use the `gh-pages`. Do you want the generated site to be in the project source code, because I think it would be better if the generated site lived in a different branch just to keep it separated from the reset of the project.

**Comment by Mahmoudz** [comment]
@computerfr33k when I try to merge the automated PR from Travis for the site I get this: any idea how to merge this without using my command line?


screen shot 2017-04-17 at 5 20 32 pm

**Comment by computerfr33k** [comment]
There is no PR to merge, it force pushes to the gh-pages branch and as u can see has the latest code already.

**Comment by Mahmoudz** [comment]
Sorry I meant to say compare the PR.. Anyway I didn't noticed the change was there already, cause when I visited the docs, I got the same problem [http://laradock.io/guides/](http://laradock.io/guides/) I though it wasn't merged, apparently it's just the doc guide link wasn't solved yet. Thanks

**Comment by computerfr33k** [comment]
Did u change the GitHub pages settings to use the gh-pages branch instead of the /docs folder from master? Because I suspect you haven't changed that setting.

**Comment by Mahmoudz** [comment]
@computerfr33k I thought I did that :P I just did it again now. Yes this should solve the issue. Thanks again.

**Pull request merged**
