### PR TITLE
Removes hard version for MySQL.

### PR DESCRIPTION
**Pull request by eltiare**
This allows for installing older versions of MySQL, this brings the code in alignment with current docs.

##### I completed the 3 steps below:

- [X] I've read the [Contribution Guide](http://laradock.io/contributing).
- [X] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [X] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by bestlong** [comment]
Why not use latest or 5.6/5.7 version?

**Comment by eltiare** [comment]
This lets people decide which version they're going to use, as is stated 
in the docs. If you hard code it in the Dockerfile then they can't 
specify which is installed in the .env file.

**Comment by eltiare** [comment]
Right now this only installs 8.0, which is a developmental version.

**Comment by bestlong** [comment]
please refer #1391 

In Dockerfile ARG instruction has a default value is better then nothing.

even if change .env file `MYSQL_VERSION=8.0` to `MYSQL_VERSION=5.7`
run `docker-compose build` always show 8.0 info
real version please use `docker inspect <image id>` command to check.

**Comment by eltiare** [comment]
I couldn't get it to install 5.7 until I changed this. I ran it multiple times, removing the containers before each attempt. I kept getting version 8 installed (both reported and in all actuality).

**Comment by bestlong** [comment]
#1426

**Comment by ryancwalsh** [comment]
I think https://github.com/laradock/laradock/issues/1392#issuecomment-383631421 fixed it for me.

**Pull request closed without merging**
