### PR TITLE
Nginx Proxy image

### PR DESCRIPTION
**Pull request by dlnsk**
Nginx Proxy is magnificent image!
No more juggling with ports! Start nginx, apache as many as you like at the same time with different PHP versions (if you want). Phpmyadmin, adminer, node may work simultaneously on beautiful domains instead of horrible ports.

It has more options. See: https://github.com/jwilder/nginx-proxy

### CODE REVIEW

**Comment by Bonobomagno** [comment]
Omg! I was searching this for a while. Thank for the commit!

**Comment by Mahmoudz** [comment]
@dlnsk that's looks very nice could you please update the docs "include the container in the list of available containers, for people to know it exist..", also "you can add a little section explaining for other users how to use or in case there's anything special they need to know.." Thanks

**Comment by dlnsk** [comment]
@Bonobomagno 
> need some fix becouse of 503 error
It works fine. Be sure that you were update your own .env file

**Comment by haringsrob** [comment]
I have updated my master to have the merge conflicts resolved: https://github.com/haringsrob/laradock

**Comment by Bonobomagno** [comment]
Why still pending?

**Comment by Mahmoudz** [comment]
@Bonobomagno this is great feature but this PR has some conflict, and needs serious testing by someone to confirm it's working. Can you help with this, basically just fix the conflict and test it locally, make sure it's not affecting other things. Then let us know to merge it quickly. Best,

**Comment by gulien** [comment]
@Mahmoudz @dlnsk Jwilder provide a awesome reverse-proxy for sure! That's said, I've you considered using https://traefik.io/ instead?

**Comment by makowskid** [comment]
Massively outdated PR, untested, a lot of conflicts. Also might be not needed anymore, we already have Traefic image incorporated.

**Pull request closed without merging**
