### PR TITLE
Added queue worker to workspace as command

### PR DESCRIPTION
**Pull request by leu2tm**

### CODE REVIEW

**Comment by leu2tm** [comment]
When using some sort of automatic deployment, it's kinda cumbersome to navigate into the container and then start the process through a script.

Also when just trying to restart/upping the container again, you'll have to repeat the procedure.

**Comment by scoutman57** [comment]
As this is project specific, why don't you create a bash script or just maintain this in your file? As this does not affect everyone (people not using worker queues). Just my thoughts.

**Comment by leu2tm** [comment]
Until now I have maintained my own file, but I thought this would be great for people who uses workers, and even for people that doesn't use it yet.

But if you feel like it you may close this PR.

**Comment by philtrep** [comment]
@leu2tm First off, thank you for the PR 😃.

I agree with @scoutman57 , this seems a bit too project specific to be done in this way.

Could we make this a build argument instead? People who want to do the same would just have to set `RUN_ARTISAN_QUEUE` to true.

Just write a little doc to go along with it and I think we're golden.

**Comment by leu2tm** [comment]
@philtrep sounds reasonable, i'll look into it :)

**Comment by scoutman57** [comment]
To piggy back off what @philtrep  stated. 

I think it could just be a `RUN_ARTISAN` to true or something similar that will execute different things that you need like migrations or something. This could even be extended to composer and npm.

**Comment by leu2tm** [comment]
@scoutman57 are you suggesting that ```RUN_ARTISAN``` should take in a string, so it can run artisan commands?

**Comment by scoutman57** [comment]
that or an array of params. Not sure which would work best since some artisan command require additional params such as `artisan migrate --seed`

**Comment by leu2tm** [comment]
@scoutman57 Hmm I think it would be best to scope it queue first, since some might use migration or other custom commands in a certain order.

**Comment by leu2tm** [comment]
I started using ```docker-compose run -d workspace php artisan queue:work``` as it seems like a better way to start queue worker.

**Pull request closed without merging**
