### PR TITLE
Added possibility of configure PUID for PHP-FPM

### PR DESCRIPTION
**Pull request by shov**
It could be useful in case one deploys on remote where are several users and a project already rolled out by user that has id of not 1000; then PHP can't work with FS properly. It possible to change PUID right in Dockerfile, but probably better have a possibility to do it in .env

##### I completed the 3 steps below:

- [x] I've read the [Contribution Guide](http://laradock.io/contributing).
- [ ] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by shov** [comment]
@bestlong can you check it, it's really important, cause using Laradock becomes not possible on manually configured instances. I can't provide anyone with access to my own user on a remote server, I'm going to create a devops user that has not 1000 user id

**Comment by shov** [comment]
#2305 looks as more complete solution

**Comment by shov** [comment]
@lanphan you guys agree but no one merge it :(

**Comment by lanphan** [comment]
Hi, I merged #2305 already.
Thanks for your remind.

**Pull request closed without merging**
