### PR TITLE
change env var DATA_SAVE_PATH default value avoid lost data

### PR DESCRIPTION
**Pull request by bestlong**
default put data directory in /tmp, if to long not use/update it, os reboot will auto cleanup.

### CODE REVIEW

**Comment by sixlive** [comment]
@bestlong any reason to use a system (user) level directory and not something local to the project?

**Comment by bestlong** [comment]
Hi @sixlive default is DATA_SAVE_PATH=/tmp

when userA login up mysql container use /tmp/mysql folder, then userB login same server up mysql container also use /tmp/mysql folder, i think that is not good. so i change it use ~/.laradock.

**Comment by bestlong** [comment]
This solution encounter other problem

when userA (ubuntu) run
```
ubuntu@aws-1:~/laradock$ pwd
/home/ubuntu/laradock
ubuntu@aws-1:~/laradock$ diff .env env-example
76c76
< NGINX_HOST_HTTP_PORT=1080
---
> NGINX_HOST_HTTP_PORT=80
ubuntu@aws-1:~/laradock$ docker-compose up -d nginx
Starting laradock_applications_1
laradock_workspace_1 is up-to-date
laradock_php-fpm_1 is up-to-date
Recreating laradock_nginx_1
ubuntu@aws-1:~/laradock$ docker-compose ps
         Name                        Command              State                      Ports
-------------------------------------------------------------------------------------------------------------
laradock_applications_1   /true                           Exit 0
laradock_nginx_1          nginx                           Up       0.0.0.0:443->443/tcp, 0.0.0.0:1080->80/tcp
laradock_php-fpm_1        docker-php-entrypoint php-fpm   Up       9000/tcp
laradock_workspace_1      /sbin/my_init                   Up       0.0.0.0:2222->22/tcp
ubuntu@aws-1:~/laradock$
```

then userB (allen) do
```
allen@aws-1:~/laradock$ pwd
/home/allen/laradock
allen@aws-1:~/laradock$ diff .env env-example
76c76
< NGINX_HOST_HTTP_PORT=2080
---
> NGINX_HOST_HTTP_PORT=80
allen@aws-1:~/laradock$ docker-compose up -d nginx
Recreating laradock_applications_1
Recreating laradock_workspace_1
Recreating laradock_php-fpm_1
Recreating laradock_nginx_1
allen@aws-1:~/laradock$ docker-compose ps
         Name                        Command              State                      Ports
-------------------------------------------------------------------------------------------------------------
laradock_applications_1   /true                           Exit 0
laradock_nginx_1          nginx                           Up       0.0.0.0:443->443/tcp, 0.0.0.0:2080->80/tcp
laradock_php-fpm_1        docker-php-entrypoint php-fpm   Up       9000/tcp
laradock_workspace_1      /sbin/my_init                   Up       0.0.0.0:2222->22/tcp
allen@aws-1:~/laradock$
```
It's run ReCreating container and nginx port mapping to 2080 (userA is 1080).

docker-compose seems not suitable for multiple user working same time.

**Comment by bestlong** [comment]
found docker-compose  usage information:
```
Options:
  -p, --project-name NAME     Specify an alternate project name (default: directory name)
```
for multi-user solution.

**Comment by bestlong** [comment]
close and redo.

**Comment by bestlong** [comment]
#972

**Pull request closed without merging**
