### PR TITLE
Install supervisord in the workspace

### PR DESCRIPTION
**Pull request by amorZhu**
##### I completed the 3 steps below:

- [x] I've read the [Contribution Guide](http://laradock.io/contributing).
- [x] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by shov** [comment]
I know that supervisord is available in php-worker container, what is the reason to have it in the workspace?

**Comment by amorZhu** [comment]
Because some people are used to using workspace instead of php-worker.

**Comment by shov** [comment]
Some people could be used to using supervisord everywhere, couldn't they?

**Comment by amorZhu** [comment]
@shov yes. Some people can use it in php-worker or in workspace.

**Comment by lanphan** [comment]
I agree to have option to be able to install Supervisord in workspace. However, would you please help to the same installation steps / configurations and example files for Supervisord like in php-worker? It's better if you update document to let user know how to enable and use Supervisord in workspace as well.

Thanks.

**Comment by amorZhu** [comment]
@lanphan Yes, I try to allow users to customize the configuration in the worksapce/supervisord directory.

**Comment by amorZhu** [comment]
@lanphan I update document and add config.

**Comment by glebgoloborodko** [comment]
Good, but how to use it in workspace now? )

**Pull request merged**
