### PR TITLE
Let's starting CI

### PR DESCRIPTION
**Pull request by bestlong**
use Travis CI run docker-compose build, see my fork project

* https://travis-ci.org/bestlong/laradock

### CODE REVIEW

**Comment by Mahmoudz** [comment]
@bestlong that's amazing, I was just working on another travis integration for auto generating the docs as recommended by @computerfr33k. I wonder now how to keep both files or probably there's a way to point to different files from the travis dashboard!

**Comment by bestlong** [comment]
@Mahmoudz Quick answer:
1. Split document to independent project.
2. use another CI service.
Any idea ?

**Comment by computerfr33k** [comment]
I will do some experimenting with Travis to figure out a solution to being able to build containers and documentation without splitting the project. This should be possible by using Travis build matrixs and defining environment variables to determine what commands should be run in the script.

**Comment by computerfr33k** [comment]
I have implemented matrix builds for travis to build both docker images & docs. See https://github.com/laradock/laradock/pull/808

**Comment by Mahmoudz** [comment]
@bestlong I've merged @computerfr33k PR #808 which contains your PR. 

This seems working perfectly, but I never saw the site actually updated!!
- I commit a change to the docs
- travis start and exist with no error
- I go to the site URL and I don't see the changes!
- I tried hard reload and refreshes.. not updating.

Any hint!?

**Pull request closed without merging**
