### PR TITLE
add nvm NVM_NODEJS_ORG_MIRROR

### PR DESCRIPTION
**Pull request by amorZhu**
##### I completed the 3 steps below:

- [x] I've read the [Contribution Guide](http://laradock.io/contributing).
- [ ] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by amorZhu** [comment]
Chinese users install nvm very slowly, I checked the nvm documentation and added the NVM_NODEJS_ORG_MIRROR parameter to allow users to choose.

**Comment by amorZhu** [comment]
Sorry, this submission is problematic. I just wanted to update the nvm problem. And to ask questions about modifying the ubuntu source, but the two submissions were submitted, I closed, and I am correcting my mistake.

I want to update the workspace ubuntu sources.list file, but I am getting an error and ask for help.

- I create sources.sh file and add to workspace path.
- I modified the workspace Dockfile.
Wrong when executed:
`
Step 12/231 : RUN if [ ${CHANGE_SOURCE} = true ]; then chmod +x /tmp/sources.sh &&     /bin/bash /tmp/sources.sh aliyun  ;fi
 ---> Running in 82d401b2e031
/bin/sh: 1: [: =: unexpected operator`
sources.sh file:
- I will submit my changes to my github repository and ask for help.

**Comment by carveybunt** [comment]
@amorZhu 大佬，这个报错解决了吗？我按照您的操作现在到了报错这步了。

**Comment by amorZhu** [comment]
> @amorZhu 大佬，这个报错解决了吗？我按照您的操作现在到了报错这步了。

没时间解决，你报错信息粘出来看看

**Comment by amorZhu** [comment]
> @amorZhu 大佬，这个报错解决了吗？我按照您的操作现在到了报错这步了。

看一下这个，[解决 Laradock 国内拉取镜像时非常慢的问题](https://segmentfault.com/a/1190000021076776)

**Pull request closed without merging**
