### PR TITLE
Add BBC Audio Waveform Image Generator

### PR DESCRIPTION
**Pull request by makowskid**
## Description
Added BCC audiowaveform support.

audiowaveform is a C++ command-line application that generates waveform data from either MP3, WAV, FLAC, or Ogg Vorbis format audio files. Waveform data can be used to produce a visual rendering of the audio, similar in appearance to audio editing applications.

Waveform data files are saved in either binary format (.dat) or JSON (.json). Given an input waveform data file, audiowaveform can also render the audio waveform as a PNG image at a given time offset and zoom level.

## Motivation and Context
This software is needed for audio related projects

## Types of Changes

- [] Bug fix (non-breaking change which fixes an issue).
- [X] New feature (non-breaking change which adds functionality).
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Definition of Done Checklist:

- [X] I've read the [Contribution Guide](http://laradock.io/contributing).
- [X] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [X] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by makowskid** [comment]
Can you please merge this one finally?  👍  :-)

**Comment by loungecrasher** [comment]
Hello, can you please merge this one?  Thanks :)

**Comment by gachowy** [comment]
Great tool! Will be very useful :)

**Comment by Cyber5an** [comment]
Please merge, important one

**Comment by tjura** [comment]
I really need that!

**Comment by makowskid** [comment]
hello? it's been more than a month, what's going on guys?

**Comment by lanphan** [comment]
@makowskid Thanks so much, merged.

**Comment by makowskid** [comment]
Thanks for merging! 👍

**Pull request merged**
