### PR TITLE
fix issue #453

### PR DESCRIPTION
**Pull request by armandojose0009**
hi, i fix a problem with php-fpm and rabbitmq, only i add this line RUN docker-php-ext-install bcmath  to Dockerfile-70. this fix the problem with phpamqplib bcadd()

### CODE REVIEW

**Comment by philtrep** [comment]
@armandojose0009 These are the wrong branches

**Comment by armandojose0009** [comment]
what branches i can use??

**Comment by philtrep** [comment]
@armandojose0009 Create a PR from your fork to master. This one is from a alternate version of the project to master.

**Comment by armandojose0009** [comment]
[image: Imágenes integradas 1]
hi i was try made a new pull request to master this message show me!

**Pull request closed without merging**
