### PR TITLE
add pgadmin backup 

### PR DESCRIPTION
**Pull request by zuohuadong**
Added pgadmin backup required for the file.
Binary file path: `/ usr / bin`
like:
Markdown

Now, it can use backup for postgres
Markdown

### CODE REVIEW

**Comment by Mahmoudz** [comment]
@zuohuadong can you add a little documentation for that?

**Comment by mikeerickson** [comment]
@zuohuadong @Mahmoudz @appleboy Has this been completed?

**Comment by Mahmoudz** [comment]
@mikeerickson doesn't seem complete yet. Let's keep it there for now it could inspire other's to finish it.

**Comment by zuohuadong** [comment]
Sorry, recently more busy, there are some problems.
I will consider a better way to achieve.

**Comment by appleboy** [comment]
@zuohuadong Please also add a little document.

**Comment by zuohuadong** [comment]
in this https://github.com/laradock/laradock/pull/1093 
and https://github.com/laradock/laradock/pull/1094

**Pull request closed without merging**
