### PR TITLE
Added Php-fpm 7.2 and made default on env-example

### PR DESCRIPTION
**Pull request by spyridonas**
##### I completed the 3 steps below:

- [] I've read the [Contribution Guide](http://laradock.io/contributing).
- [] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by Chouhada** [comment]
Line 11 in env-example needs 72 adding as a valid value

**Comment by samijnih** [comment]
Why does the travis build failed?

**Comment by spyridonas** [comment]
Running in 7fc775a7a408
pecl/swoole requires PHP (version >= 7.0.0), installed version is 5.6.33-

When Travis does tests for php56, it fails on this part

**Comment by DenzoNL** [comment]
Could someone take a look at this soon? It would be nice to have PHP 7.2 in Laradock for Laravel 5.6 and the Argon hashing algorithm :)

**Comment by spyridonas** [comment]
Until it's accepted you can modify the Dockerfile71 and make it say

FROM laradock/php-fpm:2.0-72

And you should have php 7.2.

**Comment by bestlong** [comment]
Sorry, I was merge PHP 7.2 support from #1382.

**Pull request closed without merging**
