### PR TITLE
Add console port and fix environments for minio

### PR DESCRIPTION
**Pull request by memochou1993**
## Description

Environment keys `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` are deprecated, and MinIO Console needs a static port.

```
minio_1                | WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
minio_1                |          Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
minio_1                | API: http://172.23.0.2:9000  http://172.24.0.2:9000  http://127.0.0.1:9000 
minio_1                | 
minio_1                | Console: http://172.23.0.2:41665 http://172.24.0.2:41665 http://127.0.0.1:41665 
minio_1                | 
minio_1                | Documentation: https://docs.min.io
minio_1                | 
minio_1                | WARNING: Console endpoint is listening on a dynamic port (41665), please use --console-address ":PORT" to choose a static port.
```

## Motivation and Context

Changed environment keys to `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD`, and chose `9001` as default port for MinIO Console.

## Types of Changes

- [X] Bug fix (non-breaking change which fixes an issue).
- [] New feature (non-breaking change which adds functionality).
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Definition of Done Checklist:

- [X] I've read the [Contribution Guide](http://laradock.io/contributing).
- [X] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [X] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by NisharunnisaShaik** [comment]
Hi @memochou1993 Updating port to 9001 did it worked for you ? I am also facing the same issue, I have updated the Minio_root_User & Minio_root_Password & tried with different port still i am getting the same error. Any suggestions ?

**Comment by memochou1993** [comment]
Hi @NisharunnisaShaik Yes, these changes worked for me. Did you update Dockerfile and add a console port to docker-compose.yml?
Or you may try this: https://github.com/memochou1993/minio-docker-compose Hope this helps

**Comment by NisharunnisaShaik** [comment]
@memochou1993 I am deploying minio on Kubernetes Cluster & not using Docker-compose , So i am wondering how can i add it in my yaml file

**Comment by memochou1993** [comment]
Could you provide your YAML file?

**Comment by NisharunnisaShaik** [comment]
Hi @memochou1993 

Below is my Service.yml File for Minio 

   ```
apiVersion: v1
    kind: Service
   metadata:
   name: minio-service
  spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    # Looks for labels `app:minio` in the namespace and applies the spec
    app: minio-service
```

Below is my Deployment.yml file 

```

apiVersion: apps/v1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: minio
  #namespace: minio
spec:
  selector:
    matchLabels:
      app: minio # has to match .spec.template.metadata.labels
  strategy:
    # Specifies the strategy used to replace old Pods by new ones
    # Refer: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
    type: Recreate
  template:
    metadata:
      labels:
        # This label is used as a selector in Service definition
        app: minio
    spec:
      # Volumes used by this deployment
      volumes:
      - name: minio-data
        # This volume is based on PVC
        persistentVolumeClaim:
          # Name of the PVC created earlier
          claimName: nfs-pvc
      containers:
      - name: minio
        # Volume mounts for this container
        volumeMounts:
        # Volume 'data' is mounted to path '/data'
        - name: minio-data
          mountPath: "/data"
        # Pulls the lastest Minio image from Docker Hub
        image: minio/minio:RELEASE.2021-07-12T02-44-53Z
        args:
        - server
        - /data
        env:
        # MinIO access key and secret key
        - name: MINIO_ROOT_USER
          value: "minio"
        - name: MINIO_ROOT_PASSWORD
          value: "minio123"
        ports:
        - containerPort: 9000
        # Readiness probe detects situations when MinIO server instance
        # is not ready to accept traffic. Kubernetes doesn't forward
        # traffic to the pod while readiness checks fail.
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
        # Liveness probe detects situations where MinIO server instance
        # is not working properly and needs restart. Kubernetes automatically
        # restarts the pods if liveness checks fail.
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
---
```

**Comment by memochou1993** [comment]
@NisharunnisaShaik I'm not sure. Console port should be exposed. Maybe you can open an issue at [minio/minio](https://github.com/minio/minio). I'm wondering too. 😅

**Comment by zhang10609** [comment]
@NisharunnisaShaik I had the same issue with you, and we can add the "--console-address" parameter in the yaml file like below:
In the Deployment.yml file add the "--console-address" and ":9001" in the args field as below:
        args:
        - server
        - --console-address
        - :9001
        - /data
In the Service.yml file modify the 9000 to 9001 like below:
ports:
 - port: 9001
   targetPort: 9001
   protocol: TCP

And then update the yaml for the deployment and service. Finally you will access the minio by UI successfully.

**Comment by LeartBeqiraj** [comment]
@NisharunnisaShaik Have you been able to fix this? I have the same case as you and I run into the same issue. Thanks

**Comment by MouadBH** [comment]
Thanks @memochou1993 it works.

**Comment by ArunaLakmal** [comment]
> @NisharunnisaShaik I had the same issue with you, and we can add the "--console-address" parameter in the yaml file like below:
> In the Deployment.yml file add the "--console-address" and ":9001" in the args field as below:
> args:
> - server
> - --console-address
> - :9001
> - /data
> In the Service.yml file modify the 9000 to 9001 like below:
> ports:
> 
>     * port: 9001
>       targetPort: 9001
>       protocol: TCP
> 
> 
> And then update the yaml for the deployment and service. Finally you will access the minio by UI successfully.

This didn't work and getting this distributed mode error:
```
ERROR Invalid command line arguments: Incorrect number of endpoints provided [/storage --config-dir=/config]
      > Please provide an even number of endpoints greater or equal to 4
      HINT:
        For more information, please refer to https://docs.min.io/docs/minio-erasure-code-quickstart-guide
```

Any idea?

**Comment by ArunaLakmal** [comment]
Dynamic port exposed and console was accessible any idea to fix this?
`oc port-forward pods/minio-5b84955bdd-km7gv 36853:36853`

**Comment by zhang10609** [comment]
> Dynamic port exposed and console was accessible any idea to fix this?
> `oc port-forward pods/minio-5b84955bdd-km7gv 36853:36853`

Did you have the same problem with me?  May be the error is not the same with me and you can find the warning in the minio log like below. If you have the same WARNING as below, could you pls to attach your yaml file here?
**WARNING: Console endpoint is listening on a dynamic port (41665), please use --console-address ":PORT" to choose a static port.**

**Pull request merged**
