### PR TITLE
date.timezone clarity on php-fpm

### PR DESCRIPTION
**Pull request by hounded**
After 4 hours lost to finding that the timezone for the application is set in laravel.ini

### CODE REVIEW

**Comment by appleboy** [comment]
Why create new file for single line setting?

**Comment by hounded** [comment]
It was for clarity, if I saw a file timezone or datetime, I would have avoid a few hours of trying to change timezone in the workspace. 
Hey it is non-critical, maybe it just needs better clarity in the doc's on how to change timezone 

    workspace:
        build:
            context: ./workspace
            args:
                - TZ=America/New_York

does not cut it. Also as i'm running symfony it did not occur to me to look in laravel.ini

**Comment by Mahmoudz** [comment]
I think the best thing is here, is to remove both .ini files datetime and laravel and replace them with some central ini file, for any php project, and have it well documented. I understand why you would get lost especially if you're not laravel developer you wouldn't open that file. so a generic one can help us all. Please share your thoughts.

**Comment by hounded** [comment]
Agreed, closing on the option to have a central .ini file for any php project

**Pull request closed without merging**
