### PR TITLE
Split `docker-compose.yml` + `env-example` into smaller files

### PR DESCRIPTION
**Pull request by vwchu**
See Issue #1053. Documentation still needs some work.

##### Make sure you completed the basic 3 steps below:

- [x] I've read the simple [Contribution Guide](http://laradock.io/contributing).
- [ ] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by Mahmoudz** [comment]
@vwchu that looks fantastic. Thanks for the effort you put. 

I tried testing this PR locally, and got some errors, so not sure if it's complete yet?

I noticed you aren't in the chat room on Gitter, so I invited you to discuss this further. Just ping me whenever you're in there for a quick chat. If you prefer other tools like Skype, Hangout.. let me know. 

Thanks,

**Comment by vwchu** [comment]
@Mahmoudz Thanks for adding me to the Gitter.

I know this PR is huge, and a lot of breaking changes. I would create a separate `develop` or `laradock-next` branch for this one as oppose to merge it directly into the master. Probably, a major version, 6. As such there is a lot of work to be done with regards to updating the documentation, documentation for the script, testing, additional test cases, improvements to the script, etc.

When I have a chance, I will update the documentation and add documentation for the script. 

With regards to testing, I am not sure how I will be able to test every combination of containers, since I usually only use the basic ones (nginx, apache2, php-fpm, workspace, mysql) and am not familiar with many of the containers. In theory, executing the correct command with the script should generate the same `.env` and functionally the same `docker-compose.yml`. But there could some differences. Perhaps help from the community.

**Comment by Mahmoudz** [comment]
@vwchu yes this is a major change it's gonna be version 7 I guess since I don't like number 6 :P 

It would be better creating a separate branch for this, I'm gonna invite you to become an Admin on this repository, so you'll have more freedom and control. 

The documentation is a big part of the project for sure, but let's first make sure this works as expected. We can later improve the scripts and add more tests.. 

Regarding testing every combination, this is not supported yet. This can be a separate task by itself.

Can you write here or somewhere else how to execute the script properly (basic documentation) so I can help you with this. 

If the scripts are building a `.env` and `docker-compose.yml` files for the required containers, we can keep everything the same (for travis) and just execute your script that generates those 2 files before executing our existing travis scripts to run the tests.

**Comment by vwchu** [comment]
```
scripts/laradock.sh <command> [options] <args...>

COMMANDS:

  environvars                 Alias for environvars:template
  environvars:template        Generates a environment file from the templates
  environvars:evaluate        Evaluates the template against a given set of user-defined
                              variable values. Substitutes the default values with the
                              values provided by the user.

  dockercompose               Alias for dockercompose:args
  dockercompose:args          Generates the --file arguments for docker-compose

ENVIRONVARS (For all subcommands)

  -a, --all                   Include all built-in templates in the output (default)
  -o, --output <output>       File to write generated environment file to (default: stdout)

ENVIRONVARS:TEMPLATE

  <template...>               Built-in or custom templates to include.
                              If no template is provided, include all built-in templates.
                              If a template is include, only output that template.
                              Built-in templates are specified based on their name, i.e.:
                              `nginx`, `apache2`, `php-fpm`, etc. 
                              Custom templates are specified based on their directory
                              path location: `<custom>/.env.example`.

ENVIRONVARS:EVALUATE

  -t, --template <template>   Input template to use as output (default: stdin)

  [overrides...]              List of files containing the user-defined values
                              to override or substitute the default values in the
                              templates. If none is provided, the output is the same
                              as the template. Only variables in the template will be
                              outputted. Variables not in the template are excluded.

DOCKERCOMPOSE

DOCKERCOMPOSE:ARGS

  -a, --all                   Include all built-in `docker-compose.yml` files (default)

  <compose-file...>           List of `docker-compose.yml` files to include in
                              the output, built-in and custom. If no `docker-compose.yml`
                              files are specified, includes all built-in files.
                              If a compose file is specified, only output that file.
                              Built-in compose file are specified based on their name, i.e.:
                              `nginx`, `apache2`, `php-fpm`, etc. 
                              Custom templates are specified based on their directory
                              path location: `<custom>/docker-compose.yml`.
```

**Comment by vwchu** [comment]
Close in favour of https://github.com/laradock/laradock/tree/laradock-next

**Comment by vwchu** [comment]
Hi @Mahmoudz , the current implementation for the most part works. But unfortunately, I find that my implementation of the CLI is kind of clumsy and not very elegant or easy to use. I still stand by my original idea of splitting the files, but need a better way managing it. And I intend to fix that.

However, until I can get an implementation that is more usable, I think I should delete the branch I created `laradock-next` and work on it from my personal repo. I am looking at an interface similar to the proposed CLI, but will see. I will keep you posted.

**Comment by Mahmoudz** [comment]
@vwchu totally agree. I'm a big fan of the idea. And I think the CLI would be a killer feature, as it allows us to make our code modular and easier to update.. In addition to better ways of generating and lunching containers.. Looking forward, and thanks for the effort.

**Comment by vwchu** [comment]
HI @Mahmoudz , I've made significant progress in the past few days. I have reposted the `laradock-next` branch to let others test drive it. Still need to update documentation and add additional commands.

The current usage is as follows:
```
laradock build <options...> <images...>
  Generate the necessary `.env` file to run docker-compose
    images (String) (Default: all included images)
      Automatic run `docker-compose build` on the listed of Docker images.
    --envvars=./.laradock (Default: String|Path)
      Env variables file with the variables specific to the project.
      aliases: -E <value>
    --output (Path) (Default: ./.env)
      Output Env file path to be generate.
      aliases: -O <value>, --env <value>
    --skip-dockerbuild (Boolean) (Default: false)
      Skip `docker-compose build`.
      aliases: -d
    --env-example=./.laradock.example (Default: String|Path)
      Env example file to be used as the template.
      aliases: -e <value>
    --yes (Boolean)
      Automatic yes to prompts. Assume "yes" as answer to all prompts and run non-interactively.
      aliases: -y

laradock dockercompose <options...> -- <arguments...>
  Execute `docker-compose` with the given arguments.
    arguments (String)
      Arguments and options to forward to the `docker-compose` command.
    --env (Path) (Default: ./.env)
      Environment variable file to extract module list.
      aliases: -E <value>

laradock down <options...> -- <arguments...>
  Stop and remove containers and networks, optionally volumes and images as well. Execute `docker-compose down` with the given arguments.
    arguments (String)
      Arguments and options to forward to the `docker-compose` command.
    --env (Path) (Default: ./.env)
      Environment variable file to extract module list.
      aliases: -E <value>

laradock help <commands...>
  Shows help for the CLI.
    commands (String) (Default: all)
      Commands and command groups.

laradock init <options...> <project-name> <modules...>
  Initializes Laradock in existing Laravel projects.
    project-name (String) (Default: basename of APPLICATION)
      Sets the project name.
    modules (String|Path) (Default: all builtin modules)
      Modules to include within the output.
    --envvars (Path) (Default: ./.laradock)
      File path to sample project-specific variables file to be generate.
      aliases: -E <value>
    --output (Path) (Default: ./.env)
      Output Env file path to generate when the variables file is evaluated.
      aliases: -O <value>, --env <value>
    --env-example (Path) (Default: ./.laradock.example)
      File path to sample Env example file to be generate.
      aliases: -e <value>
    --yes (Boolean)
      Automatic yes to prompts. Assume "yes" as answer to all prompts and run non-interactively.
      aliases: -y

laradock install <options...> <target>
  Installs this CLI at the given target path
    target (Path) (Default: ./laradock)
      Destination path to output the laradock executable script.
    --yes (Boolean)
      Automatic yes to prompts. Assume "yes" as answer to all prompts and run non-interactively.
      aliases: -y

laradock ssh <options...> <container> -- <arguments...>
  Alias for: tty

laradock tty <options...> <container> -- <arguments...>
  Execute `docker-compose exec -it <container> bash` with the given arguments.
  aliases: ssh
    container (String)
      Docker container to attach a terminal to.
    arguments (String)
      Arguments and options to forward to the `docker-compose` command. Arguments before `--` are docker-compose options, after `--` are bash arguments.
    --env (Path) (Default: ./.env)
      Environment variable file to extract module list.
      aliases: -E <value>

laradock up <options...> -- <arguments...>
  Create and start containers. Execute `docker-compose up` with the given arguments.
    arguments (String)
      Arguments and options to forward to the `docker-compose` command.
    --env (Path) (Default: ./.env)
      Environment variable file to extract module list.
      aliases: -E <value>
```

If you set `ENABLE_PRIVATE_COMMANDS=true`, there are more internal commands for debugging.
Verbosity can also be set `VERBOSE=<some number between 0 and 7>` 0 being silent and 7 being more verbose.

**Comment by Mahmoudz** [comment]
@vwchu looks fantastic.

**Pull request closed without merging**
