### PR TITLE
Improve php-fpm zip extension module to support php7.4

### PR DESCRIPTION
**Pull request by amiraliio**
##### I completed the 2 steps below:

- [x] I've read the [Contribution Guide](http://laradock.io/contributing).
- [] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by bestlong** [comment]
All PHP versions get syntax error

**Comment by amiraliio** [comment]
> All PHP versions get syntax error

**Comment by bestlong** [comment]
only 7.3 build pass

7.4 build error:
```shell
Step 8/146 : RUN  if [${LARADOCK_PHP_VERSION} -lt 7.3]; then     set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     apt-get install -yqq     apt-utils     libzip-dev zip unzip &&     docker-php-ext-configure zip --with-libzip &&     docker-php-ext-install zip &&     php -m | grep -q 'zip'; else     set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     apt-get install -yqq     apt-utils     libzip-dev zip unzip &&     docker-php-ext-configure zip --with-libzip &&     docker-php-ext-install zip &&     php -m | grep -q 'zip' ;fi
1247 ---> Running in 04d05c4a5c92
1248/bin/sh: 1: [7.4: not found
1249+ apt-get update -yqq
1250+ pecl channel-update pecl.php.net
1251Updating channel "pecl.php.net"
```

**Comment by bestlong** [comment]
Ref #2461

**Pull request closed without merging**
