### PR TITLE
Fix Xdebug 3 compatibility with PHP 7.3 and 7.4

### LINKED ISSUE #3083: xdebug 3.1 not work
### Context information:

**Output of `git rev-parse HEAD`**

```
{paste here}
```

**Output of `docker version`**

```
{paste here}
```

**Output of `docker-compose version`**

```
{paste here}
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
{paste here}
```

### Steps to reproduce the issue:

1.
2.
3.

### Stacktrace & Additional info:

```
{paste here}
```

image
image

image
image

image

### LINKED ISSUE #3099: xdebug version to install in php-fpm according php version doesn't work in 7.4
https://github.com/laradock/laradock/blob/b3b0b0c40fcba1fc891cb6201d3d6f01e6cebfdb/php-fpm/Dockerfile#L223

The version of xdebug that is installed according php version (7.4) is different in workspace that in php-fpm.

In my case, I needed paste [the lines that install xdebug from workspace Dockerfile](https://github.com/laradock/laradock/blob/b3b0b0c40fcba1fc891cb6201d3d6f01e6cebfdb/workspace/Dockerfile#L333) to php-fpm Dockerfile, to get debugging.
```
  if [ $(php -r "echo PHP_MAJOR_VERSION;") = "8" ]; then \
    pecl install xdebug-3.0.0; \
  else \
    if [ $(php -r "echo PHP_MAJOR_VERSION;") = "5" ]; then \
      pecl install xdebug-2.5.5; \
    else \
      if [ $(php -r "echo PHP_MAJOR_VERSION;") = "7" ] && [ $(php -r "echo PHP_MINOR_VERSION;") = "0" ]; then \
        pecl install xdebug-2.9.0; \
      else \
        if [ $(php -r "echo PHP_MAJOR_VERSION;") = "7" ] && [ $(php -r "echo PHP_MINOR_VERSION;") = "1" ]; then \
          pecl install xdebug-2.9.8; \
        else \
          if [ $(php -r "echo PHP_MAJOR_VERSION;") = "7" ]; then \
            pecl install xdebug-2.9.8; \
          else \
            #pecl install xdebug; \
            echo "xDebug 3 required, not supported."; \
          fi \
        fi \
      fi \
    fi \
  fi && \
```

### PR DESCRIPTION
**Pull request by DocLM**
## Description

Add version check to Xdebug configuration to match the check used to install Xdebug 3.
Previously only PHP 8 use v3 but now also PHP 7.4 and 7.3 need configuration adjustments to work as expected.
I've also updated Xdebug version to match the latest version (3.1.4) available on PECL at the time of writing.
Since Xdebug 3 use port 9003 as default I've added a configuration variable to allow to specify Xdebug port for php-fpm and workspace container

Fixes #3099 and #3169 if used with default configuration (probably also fixes #3083)

## Motivation and Context
Fixes issues caused by the migration to Xdebug 3 for PHP version 7.4 and 7.4.
Also add the ability to select a custom port instead of 9003 for Xdebug in workspace and php-fpm.

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Definition of Done Checklist:

- [x] I've read the [Contribution Guide](http://laradock.io/contributing).
- [x] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by PaolaRuby** [comment]
Probably also fixes https://github.com/laradock/laradock/issues/3230

**Comment by Skatox** [comment]
I would like this patch gets approved. I'm having this issue.

**Comment by wangtufly** [comment]
I would like this patch gets approved. I'm having this issue.  +1

**Comment by DocLM** [comment]
@bestlong what do you think about these changes?
A working debugger is one of the most important feature a developer should have.

**Pull request merged**
