### PR TITLE
PHP Intl

### PR DESCRIPTION
**Pull request by sashaaro**

### CODE REVIEW

**Comment by philtrep** [comment]
@sashaaro Could you explain why this is required? Is there an issue associated to this?

**Comment by dannysood** [comment]
@philtrep Even i am facing this issue as well. Some external composer packages ask for it. Homebrew provides it in stock install (as I moved my repo from homebrew to laradock) and `composer install` broke.

```
Problem 1
    - Installation request for jeremykendall/php-domain-parser 3.0.0 -> satisfiable by jeremykendall/php-domain-parser[3.0.0].
    - jeremykendall/php-domain-parser 3.0.0 requires ext-intl * -> the requested PHP extension intl is missing from your system.
  Problem 2
    - Installation request for league/uri 4.2.2 -> satisfiable by league/uri[4.2.2].
    - league/uri 4.2.2 requires ext-intl * -> the requested PHP extension intl is missing from your system.
```

**Comment by sashaaro** [comment]
Why not add Intl by default. Many packages required it

**Comment by dannysood** [comment]
@sashaaro I am getting this error when adding the changes in my local dockerfile as shown in the PR request. However i keep getting the following. To be just sure I also added google dns by adding it to daemon.json at `/etc/docker/daemon.json` but to no avail. Also this is happening only to this statement.
```
Suggested packages:
  icu-doc
The following NEW packages will be installed:
  icu-devtools libicu-dev libicu52
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 14.6 MB of archives.
After this operation, 65.6 MB of additional disk space will be used.
Err http://httpredir.debian.org/debian/ jessie/main libicu52 amd64 52.1-8+deb8u3
  404  Not Found [IP: 108.61.5.92 80]
Err http://security.debian.org/ jessie/updates/main libicu52 amd64 52.1-8+deb8u3
  404  Not Found [IP: 128.101.240.215 80]
Err http://security.debian.org/ jessie/updates/main libicu-dev amd64 52.1-8+deb8u3
  404  Not Found [IP: 128.101.240.215 80]
Err http://security.debian.org/ jessie/updates/main icu-devtools amd64 52.1-8+deb8u3
  404  Not Found [IP: 128.101.240.215 80]
E: Failed to fetch http://security.debian.org/pool/updates/main/i/icu/libicu52_52.1-8+deb8u3_amd64.deb  404  Not Found [IP: 128.101.240.215 80]

E: Failed to fetch http://security.debian.org/pool/updates/main/i/icu/icu-devtools_52.1-8+deb8u3_amd64.deb  404  Not Found [IP: 128.101.240.215 80]

E: Failed to fetch http://security.debian.org/pool/updates/main/i/icu/libicu-dev_52.1-8+deb8u3_amd64.deb  404  Not Found [IP: 128.101.240.215 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c apt-get install -y libicu-dev && pecl install intl && docker-php-ext-install intl' returned a non-zero code: 100
```

**Comment by sashaaro** [comment]
Seems It work for me long time ago. At least I have not docker's errors.
I think it is only from php-fpm. But for `composer install` should change workspace Dockerfile. 
I don't know exactly. 
Someone know better than me should correct it.
By the way you can avoid it by use run `composer install --ignore-platform-reqs`

**Comment by dannysood** [comment]
@sashaaro  composer install --ignore-platform-reqs worked for me but seems unsafe to ignore platform requirements. @philtrep Is there a better way to do it? Would really appreciate to add it to the laradock itself but if not then how can we proceed about it. So that its available for both php-fpm and cli if required.

**Comment by philtrep** [comment]
@sashaaro @dannysood This should be a build argument on both the `workspace` and `php-fpm` images. I don't think there's a better way to do this with just docker-compose.

**Comment by a-h-abid** [comment]
I'm also having this same issue. `libicu-dev` fails the build install. Anyone know how to fix it?

	Step 16/40 : RUN apt-get install -y zlib1g-dev libicu-dev g++                                                                                      
	 ---> Running in 214b167d7568                                                                                                                      
	Reading package lists...                                                                                                                           
	Building dependency tree...                                                                                                                        
	Reading state information...                                                                                                                       
	g++ is already the newest version.                                                                                                                 
	zlib1g-dev is already the newest version.                                                                                                          
	Suggested packages:                                                                                                                                
	  icu-doc                                                                                                                                          
	The following NEW packages will be installed:                                                                                                      
	  icu-devtools libicu-dev libicu52                                                                                                                 
	0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.                                                                                     
	Need to get 14.6 MB of archives.                                                                                                                   
	After this operation, 65.6 MB of additional disk space will be used.                                                                               
	Err http://httpredir.debian.org/debian/ jessie/main libicu52 amd64 52.1-8+deb8u3                                                                   
	  404  Not Found [IP: 151.101.64.204 80]                                                                                                           
	Err http://security.debian.org/ jessie/updates/main libicu52 amd64 52.1-8+deb8u3                                                                   
	  404  Not Found                                                                                                                                   
	Err http://security.debian.org/ jessie/updates/main icu-devtools amd64 52.1-8+deb8u3                                                               
	  404  Not Found                                                                                                                                   
	Err http://security.debian.org/ jessie/updates/main libicu-dev amd64 52.1-8+deb8u3                                                                 
	  404  Not Found                                                                                                                                   
	E: Failed to fetch http://security.debian.org/pool/updates/main/i/icu/libicu52_52.1-8+deb8u3_amd64.deb  404  Not Found                             
																																					   
	E: Failed to fetch http://security.debian.org/pool/updates/main/i/icu/icu-devtools_52.1-8+deb8u3_amd64.deb  404  Not Found                         
																																					   
	E: Failed to fetch http://security.debian.org/pool/updates/main/i/icu/libicu-dev_52.1-8+deb8u3_amd64.deb  404  Not Found                           
																																					   
	E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?                                                              
	ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c apt-get install -y zlib1g-dev libicu-dev g++' returned a non-zero code: 100

**Pull request closed without merging**
