### PR TITLE
Mssql support

### PR DESCRIPTION
**Pull request by cabrerabywaters**
Adds Support for MSSQL in php7.0-fpm container

### CODE REVIEW

**Comment by Mahmoudz** [comment]
@cabrerabywaters also conflict here, please solve it to merge. Thanks

**Comment by cabrerabywaters** [comment]
@Mahmoudz All set here...(Y)

**Comment by thorerik** [comment]
May I suggest bundling in the [mssql-server-linux](https://hub.docker.com/r/microsoft/mssql-server-linux/) docker image so that you can have a fully self-contained dev environment, also with MSSQL.

**Comment by cabrerabywaters** [comment]
@thorerik I use that container too but...Is there any way to integrate it with PHP-FPM that runs in this container? This is not for running a MSSQL DB, but to use PHP SQL extensions.

**Comment by Mahmoudz** [comment]
@cabrerabywaters can you a MSSQL container in Laradock, to give us more control from one place. 
See any other DB support and try to do the same, you can use the image mentioned by @thorerik as base image.

**Comment by cabrerabywaters** [comment]
@Mahmoudz Sure! let me take a look at the other DBs and I'll see what i can do ;)

**Comment by Mahmoudz** [comment]
@cabrerabywaters something simple to look at is [NEO4J](https://github.com/laradock/laradock/blob/master/neo4j/Dockerfile). Best,

**Pull request merged**
