### PR TITLE
Removing double quotes for apache php fpm configuration.

### PR DESCRIPTION
**Pull request by calebfavor**
#374

### CODE REVIEW

**Comment by philtrep** [comment]
@calebfavor First, thank you for your contribution.

I'm not sure I understand `ARG PHP_SOCKET=$PHP_SOCKET`. That would mean that you are defaulting to the environment variable `PHP_SOCKET` but you probably want the default value to be `php-fpm:9000` right?

**Comment by calebfavor** [comment]
@philtrep Yes! I was a little unclear on how those variables are passed down the images and in to the application. After reading up on it I definitley agree. Fix pushed, I will edit my post in the issue.

Cheers!

**Comment by philtrep** [comment]
@calebfavor Okay no problem, thank you very much for your contribution.

**Comment by hasangilak** [comment]
apache2_1              | 2017-09-02 10:12:01,547 INFO success: apached entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
apache2_1              | AH00526: Syntax error on line 9 of /opt/docker/etc/httpd/conf.d/10-php.conf:
apache2_1              | ProxySet: Timeout must be at least one second timeout=; fcgi://php-fpm:9000
apache2_1              | 2017-09-02 10:12:01,577 INFO exited: apached (exit status 1; not expected)

I fixed it by editing /opt/docker/etc/httpd/conf.d/10-php.conf and setting timeout=1

**Pull request merged**
