### PR TITLE
Add mailhog for mail debugging

### PR DESCRIPTION
**Pull request by wayanjimmy**
Hi I'm try to help adding mailhog for mail debugging

### CODE REVIEW

**Comment by alchimik** [comment]
please add [ssmtp](https://github.com/gagarine/docker-php/blob/master/Dockerfiles/phpfpm/7.0/Dockerfile#L24) or equivalent (i use msmtp)

**Comment by alchimik** [comment]
`mailhog/Dockerfile` file is not needed. Replace `build: ./mailhog` -> `image: mailhog/mailhog`

**Comment by philtrep** [comment]
@wayanjimmy Thanks for the PR! What @alchimik says seems about right.

**Comment by Mahmoudz** [comment]
@wayanjimmy I'm gonna merge this and later @alchimik or you can add the SMTP thingy. @wayanjimmy whenever you have time please include that container in the docs..

**Comment by drizzersilverberg** [comment]
hello, @wayanjimmy @alchimik . help me with this issue https://github.com/laradock/laradock/issues/2134, I think this would be same issue if I use mailhog too.

**Pull request merged**
