### PR TITLE
Enable PHP Opcache by default for faster PHP performance

### PR DESCRIPTION
**Pull request by jhkueh**
I would like to suggest that the `PHP Opcache` setting be set to `true` by default in the `env-example` file, so that whoever wants to run a new PHP laradock project can experience the speed right away :)

I had also added some additional `opcache` settings.

What do you guys think?

### CODE REVIEW

**Comment by a-h-abid** [comment]
I haven't used opcache myself. So.... does it affect during development? I mean, does it immediately invalidates cache if I modify php file?

**Comment by appleboy** [comment]
I don't like to enable `PHP Opcache` as the default setting.

**Comment by winfried-van-loon** [comment]
As with all dotenv settings, they are easily enabled if needed. Therefor, I would suggest keeping to the way we've got all settings available now.

I do like the option of having opcache available. It does speed up certain projects. However, in my experience, sometimes it's a bit hard to keep track of what's cached and what's not.

**Comment by mikeerickson** [comment]
@winfried-van-loon @jhkueh I completely agree, this is why it is an option.  Not every developer would want this on by default.

**Comment by winfried-van-loon** [comment]
We could, however, add in the options in `php-fpm/opcache.ini`

**Comment by mikeerickson** [comment]
@winfried-van-loon this is already an option in the `.env` file, what more is required.  I am sure this works as planned (I have it enabled for my projects)

```
https://github.com/laradock/laradock/blob/master/env-example
line: 64
```

**Comment by jhkueh** [comment]
Maybe it's just my local machine, but I can't live without Opcache. Every page load is 2-3 seconds in Laravel 5.4 without it. When it's enabled, it's less than 1s.

**Pull request closed without merging**
