### PR TITLE
541-add-linuxbrew-option

### PR DESCRIPTION
**Pull request by mikeerickson**
- [x] Add option to install `linuxbrew` 

Customize `docker-compose.yml` as follows:

```
...
- INSTALL_LARAVEL_ENVOY=false
- INSTALL_LINUXBREW=false
- PUID=1000
...
```

### CODE REVIEW

**Comment by philtrep** [comment]
@mikeerickson Works great! Just add some documentation for it in the README and I'll happily merge this.

**Comment by mikeerickson** [comment]
@philtrep sounds good, I will get it updated this evening.

**Comment by mikeerickson** [comment]
@philtrep OK, all done (I have updated the `README.md` file)  Please let me know if you need anything else.

**Comment by philtrep** [comment]
@mikeerickson Thanks for your contribution!

**Pull request merged**
