### PR TITLE
AMQP installation for all images and all php versions

### LINKED ISSUE #2891: AMQP for all services | PHP 8.0
**Is your feature request related to a problem? Please describe.**

#2871 requires only `workspace`. This issue requires all services (php-fpm, laravel-horizon, php-worker) for all PHP versions (marked in title 8.0, because it's a new one; other ones should be tested).

**Describe the solution you'd like**

Change installation script with an actual PECL version (see references in #2871).

**Describe alternatives you've considered**

[Nothing]

**Additional context**

[Nothing]

### PR DESCRIPTION
**Pull request by PavelSavushkinMix**
## Description

Unfortunately, the #2871 does not convert all images/versions. This one covers.
Closes #2891 

## Motivation and Context

Get built AMQP for all images w/o errors.

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Definition of Done Checklist:

- [x] I've read the [Contribution Guide](http://laradock.io/contributing).
- [ ] I've updated the **documentation**. (refer to [this](http://laradock.io/contributing/#update-the-documentation-site) for how to do so).
- [x] I enjoyed my time contributing and making developer's life easier :)

### CODE REVIEW

**Comment by bestlong** [comment]
also edit Github CI `.github/workflows/main-ci.yml` enable install

remove  `sed -i -- 's/AMQP=true/AMQP=false/g' .env`

**Comment by PavelSavushkinMix** [comment]
@bestlong, done.
What do you think: maybe it's better to separate GitHub Actions and Travis CI? GitHub Actions is for the default-enable services building, but Travis CI for all of them for all environments?

**Comment by bestlong** [comment]
> @bestlong, done.
> What do you think: maybe it's better to separate GitHub Actions and Travis CI? GitHub Actions is for the default-enable services building, but Travis CI for all of them for all environments?

#2907

**Comment by PavelSavushkinMix** [comment]
> > @bestlong, done.
> > What do you think: maybe it's better to separate GitHub Actions and Travis CI? GitHub Actions is for the default-enable services building, but Travis CI for all of them for all environments?
> 
> #2907

Got it.

**Pull request merged**
